### ISSUE TITLE
cumpile and ganpile issue

### ISSUE THREAD

**Issue by Rajesh-design158** [uowuo/abaddon#10]
Hello sir,,, soonly response ok?

I am have troubles cunpile on macks os and linux,, i notice that only window listed for cunpile ????? 🤢 

pls, provinde cunpile instrunction.

THanks, 
Rajesh Design LLC.

**Comment by ouwou** [comment]
no vilpy

**Comment by Rajesh-design158** [comment]
wat da???? i will unstar. s*upid fucking d*gs*it

Thanks,
Rajesh Design LLC.

**Comment by Rajesh-design158** [comment]
REOPEN THIS FCKING ISSUE NOW MADERCHOD

**Comment by ouwou** [comment]
pay me
