### ISSUE TITLE
how to change font size?

### ISSUE THREAD

**Issue by ForceFaction** [uowuo/abaddon#111]
Hi, this is more of a support question: How do i change/increase the font size? I'm running i3.

**Comment by ouwou** [comment]
try `GDK_DPI_SCALE=1.5 GDK_SCALE=1 ./abaddon` which should scale up text by 1.5
you can also alternatively try this https://stackoverflow.com/a/54160420
feel free to reopen if u still need help

**Comment by ForceFaction** [comment]
The environemnt variables didn't change anything, but the config file works. Thanks for the help :slightly_smiling_face:
