### ISSUE TITLE
"error while loading shared libraries: libssl.so.3: cannot open shared object file"

### ISSUE THREAD

**Issue by pqnhan** [uowuo/abaddon#128]
I ran a test build on Ubuntu 18.04 and got this error.
This library I remember updating on my current Ubuntu 20.04.5.

Is there a way to fix it?

**Comment by Senpai-10** [comment]
Could you provide the whole output in the terminal?

**Comment by pqnhan** [comment]
@Senpai-10 
Yes. 

![image](https://user-images.githubusercontent.com/24197589/206441410-41849984-031e-406f-9986-63c9b6e982b3.png)

**Comment by pqnhan** [comment]
@Senpai-10 
Hmm, i have tried, but not work :(
![image](https://user-images.githubusercontent.com/24197589/206454482-8be4d89f-1ee4-4ce5-90fb-2f594667edb9.png)

**Comment by pqnhan** [comment]
Has anyone here has tried to build AppImage of Abaddon?

**Comment by ouwou** [comment]
some people in the discord messed around with AppImages i think. but since im guessing your original issue is fixed ill close this for now. maybe u can open a discussion about it if u want
