### ISSUE TITLE
[Feature request] Display group DM name

### ISSUE THREAD

**Issue by KaKi87** [uowuo/abaddon#133]
Hello,

The DM list shows groups by member count, it would be nice to see those as their names instead.

Thanks

**Comment by ouwou** [comment]
should work the same as the official client now

**Comment by KaKi87** [comment]
Excellent, thanks !

But Windows & Mac builds failed, although this doesn't affect me.

**Comment by KaKi87** [comment]
Actually, there's one more thing : the window is also titled incorrectly when a group DM is selected.

Thanks

**Comment by ouwou** [comment]
good point ill fix that tomorrow (hopefully)

**Comment by ouwou** [comment]
that should do it

**Comment by KaKi87** [comment]
Perfect, thanks !
