### ISSUE TITLE
[Feature request] Select & copy embed content

### ISSUE THREAD

**Issue by KaKi87** [uowuo/abaddon#134]
Hello,

It would be nice to be able to select & copy embeds content.

Thanks

**Comment by ouwou** [comment]
as in a right click option? or as in the ability to highlight certain text and copy? if you want a right click option, "content" is a little ambiguous since embeds have a description, title, header, footer, fields, etc.

**Comment by ouwou** [comment]
does it even let you highlight and copy regular messages? i think this might be a general gtk thing

**Comment by KaKi87** [comment]
> does it even let you highlight and copy regular messages?

Yes, it does !

**Comment by ouwou** [comment]
looks like theres some weird platform-specific gtk stuff going on... i guess you can copy normal messages because they are Gtk.TextViews but not embeds because theyre generally composed of Gtk.Labels. ill have to look into it some more

**Comment by KaKi87** [comment]
Actually, I realize I can't copy selected content of normal messages either.

Nor select content of multiple messages simultaneously.

**Comment by ouwou** [comment]
are you on windows?

**Comment by KaKi87** [comment]
No, I'm on Linux.

**Comment by ouwou** [comment]
ok i think i see what's going on. should have it fixed soon 🤞

**Comment by ouwou** [comment]
ff47134dc64ac2f0fa7bfee64313b2522709b9b9 should make embeds selectable. regular messages are still behaving strange for me and only let you copy if you triple click to select all but let me know how it works on your end

**Comment by ouwou** [comment]
ill look into the titles. fundamentally i dont think theres any way to allow for selections across both title and body simultaneously since they are two distinct widgets

**Comment by KaKi87** [comment]
> fundamentally i dont think theres any way to allow for selections across both title and body simultaneously since they are two distinct widgets

There must be a way for a native app to do what a browser does, right ?

**Comment by ArjixWasTaken** [comment]
> > fundamentally i dont think theres any way to allow for selections across both title and body simultaneously since they are two distinct widgets
> 
> There must be a way for a native app to do what a browser does, right ?

well, browsers have the Selection API, [here](https://www.youtube.com/watch?v=d9SIP87IR4Q) is a video that goes into details
and [here](https://www.w3.org/TR/selection-api/) is the spec, yes it has its own spec...

I haven't worked on GTK apps so I don't even know if you can traverse a GTK widget tree, but that would be a basic requirement for this to happen.

**Comment by ArjixWasTaken** [comment]
PS: This is A LOT of work for just selecting text, and should not be smth the developer of this client needs to do.
It should be smth supported by GTK itself

**Comment by KaKi87** [comment]
I'm sorry to say that, these native-specific limitations, despite how small they seem, considerably decreases the UX compared to Discord's web app, so much that the native-specific advantages don't feel worth it.

**Comment by ouwou** [comment]
closing cuz last commit lets selecting message text work normally now. the type of selection behavior you describe just isnt something really possible for a GTK program

**Comment by KaKi87** [comment]
I'm experiencing the following error after running the latest build :

```
./abaddon: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory
```

Thanks

**Comment by ouwou** [comment]
thats probably not an issue with abaddon just something on your side. but make sure you have spdlog properly installed. you might need to symlink it somewhere. you also might be able to get some better info from googling that error

**Comment by KaKi87** [comment]
Turns out I'm experiencing this issue since 0a1138f.

I am not experiencing this issue using 38c3b0c and earlier.

**Comment by ouwou** [comment]
you wont experience the issue there because voice support wasnt merged in yet (which brought in the spdlog dependency). the package on ubuntu afaik is `libspdlog-dev`. if you still have issues id rather you open a new issue for it
