### ISSUE TITLE
[Bug] Some cursor moving shortcuts don't work in message input

### ISSUE THREAD

**Issue by KaKi87** [uowuo/abaddon#135]
Hello,

The following shortcuts don't work in Abaddon's message input :
- `Ctrl+ArrowLeft` & `Ctrl+ArrowRight` for moving cursor between whole words ;
- `Ctrl+Home` & `Ctrl+End` for moving cursor at the beginning of the first line and at the end of the last line.

Meanwhile, all other shortcuts of the same kind work :
- `Ctrl+Shift+ArrowLeft`, `Ctrl+Shift+ArrowRight`, `Ctrl+Shift+Home` & `Ctrl+Shift+End` for doing the same actions while selecting ;
- `ArrowLeft` & `ArrowRight` for moving the cursor between characters ;
- `Shift+ArrowLeft` & `Shift+ArrowLeft` for doing the same action while selecting ;
- `Home` & `End` for moving cursor at the beginning of the current line and at the end of the current line ;
- `Shift+Home` & `Shift+End` for doing the same action while selecting.

Thanks

**Comment by ouwou** [comment]
well i figured out whats causing this. i find it really strange its only those few that dont work while the others do... but either way i should have it fixed pretty soon

**Comment by ouwou** [comment]
that should take care of it let me know if theres still issues

**Comment by KaKi87** [comment]
Actually, I got a crash as soon as I tried connecting :
```
sending {"d":null,"op":1}
Segmentation fault (core dumped)
```

**Comment by KaKi87** [comment]
Turns out, after several tests, that 5a6f8ca (4034186593) is the last working build for me, i.e. 3ed51eb (4071246312) is the first one to crash.

**Comment by ouwou** [comment]
could you get a backtrace with gdb? and that commit cant be the cause since it only modifies the CI process for windows and IIRC you are on linux. also if you want you can open another issue for the crash
