### ISSUE TITLE
[CI] Add commit ID & timestamp to file name

### ISSUE THREAD

**Issue by KaKi87** [uowuo/abaddon#138]
Thanks

**Comment by ouwou** [comment]
i guess that could be useful but i dont think i can do that and keep the direct download links in the readme

**Comment by KaKi87** [comment]
How about the directory name inside the ZIP instead of the ZIP, at least ?

**Comment by ouwou** [comment]
i guess i could do that. out of curiosity whats your use case? maybe a file containing that info?

**Comment by KaKi87** [comment]
It's a really simple reason, actually : when I had to figure out since which Abaddon release did my crash issue was occuring, I downloaded a dozen versions, so I had to manually rename those, as operating systems only know `(1)`, `(2)`, etc...

Also, when using portable apps, I like to have version numbers on my files anyway so that I can quickly check whether I'm running the latest, and know which ones I did or didn't use.

**Comment by ouwou** [comment]
7e9567f9f91c0bb56f9af63b29d4443e97e158b6
