### ISSUE TITLE
System tray icon missing on Arch linux with dwm

### ISSUE THREAD

**Issue by Zander671** [uowuo/abaddon#142]
I am on Arch with dwm as my window manager. I am using the systray patch for dwm. I installed abaddon with the aur package named "abaddon". I set hide_to_tray to true in the abaddon.ini file and while abaddon hides and restores from the tray without issue, the icon is missing. Here is an image of the system tray:
![out](https://user-images.githubusercontent.com/25143634/221005544-24f8547c-f34f-45c2-8ba4-335741a178f4.png)
Clicking on this icon will hide/show the abandon window.

**Comment by ouwou** [comment]
there is no icon right now at all, so the best you can do right now is probably change it to something of your choosing until one is made
