### ISSUE TITLE
PGP chat integration

### ISSUE THREAD

**Issue by SpookySkeletons** [uowuo/abaddon#148]
I probably don't need to wax much about how much being able to communicate securely with PGP would be a killer feature.

Willing to integrate this using such desktop clients like kgpg to do the heavy lifting and simply pass messages for encode and decode as they are sent/ received?

**Comment by ouwou** [comment]
while i wont rule anything out, my goal is to reach feature parity before implementing extra things like this. ill close this for now since its not really something im gonna consider for the time being but maybe at some point in the future i may.
