### ISSUE TITLE
servers don't load correctly [BUG, i think.]

### ISSUE THREAD

**Issue by PATATAGAME554** [uowuo/abaddon#154]
hello.
on the official client discord(web app) server(s) load's, but on abaddon doesn't load nothing.

machine: iMac g3 with openbsd 7.3 (abaddon builded from source)

screen:
on the official client: ![IMG_20230425_070410_edit_28157665549869](https://user-images.githubusercontent.com/76092291/234179652-2ed73411-fde1-4ded-bdaf-67cd19ebe346.jpg)

on abaddon: 
![IMG_20230425_070403_edit_28164521736847](https://user-images.githubusercontent.com/76092291/234179765-24ad23c3-2906-47f6-96f2-d5048fb8d280.jpg)

**Comment by ouwou** [comment]
can you enable the dump ready message option under `File` and send the value of `guild_positions` and or `guild_folders` from the `.json` file it generates? either way you should be able to fix this by moving the servers around through the web client

**Comment by PATATAGAME554** [comment]
> can you enable the dump ready message option under `File` and send the value of `guild_positions` and or `guild_folders` from the `.json` file it generates? either way you should be able to fix this by moving the servers around through the web client

ok "fixed" but, where is located the `.json` file?

**Comment by ouwou** [comment]
it should be in the same directory as the executable or wherever you launched from

**Comment by PATATAGAME554** [comment]
> it should be in the same directory as the executable or wherever you launched from

"payload_ready-2023-04-25_06-51-54.json" ?

**Comment by ouwou** [comment]
yup, specifically id like the `guild_positions` and `guild_folders` arrays which are in the user_settings section

**Comment by PATATAGAME554** [comment]
> yup, specifically id like the `guild_positions` and `guild_folders` arrays which are in the user_settings section

i hope this the right thing :')

`    },
    "user_settings": {
        "activity_joining_restricted_guild_ids": [],
        "activity_restricted_guild_ids": [],
        "afk_timeout": 600,
        "allow_accessibility_detection": false,
        "animate_emoji": false,
        "animate_stickers": 2,
        "contact_sync_enabled": true,
        "convert_emoticons": false,
        "custom_status": null,
        "default_guilds_restricted": false,
        "detect_platform_accounts": true,
        "developer_mode": false,
        "disable_games_tab": false,
        "dm_spam_filter": 1,
        "dm_spam_filter_v2": 0,
        "enable_tts_command": true,
        "explicit_content_filter": 1,
        "family_center_enabled": true,
        "friend_discovery_flags": 0,
        "friend_source_flags": {},
        "gif_auto_play": false,
        "guild_folders": [
            {`

**Comment by ouwou** [comment]
looks like what you sent cut off at guild_folders. alternatively maybe you can just dm me the whole file if youre alright with that: im `mark the third#2115`

**Comment by PATATAGAME554** [comment]
> looks like what you sent cut off at guild_folders. alternatively maybe you can just dm me the whole file if youre alright with that: im `mark the third#2115`

mh, nah, thanks for the answer

**Comment by ouwou** [comment]
alright ill close then since looks like original problem was fixed. would still be helpful if you could get those two arrays, but i suspect the issue is that the first two servers in the screenshot were the last two that you joined and that caused `guild_folders` to be out of date. ill still look into it

**Comment by ouwou** [comment]
was able to replicate. should be good now
