### ISSUE TITLE
Could not load pixbuff - Windows

### ISSUE THREAD

**Issue by adam-tj** [uowuo/abaddon#160]
Hey, I am running version 0.1.10 and I am getting this error when starting the application. Running Windows 10

> (abaddon.exe:7684): Gtk-WARNING **: 13:13:53.243: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

**Comment by ouwou** [comment]
assuming youre not actually running into any issues with images loading, its safe to ignore this
