### ISSUE TITLE
Cookies/Build number could not be fetched

### ISSUE THREAD

**Issue by guyman624** [uowuo/abaddon#162]
![image](https://github.com/uowuo/abaddon/assets/82007920/e7ff926a-fd6e-4c4f-abef-628715284659)
![image](https://github.com/uowuo/abaddon/assets/82007920/f957879e-e4a0-4144-ae25-2674ff81a156)
Just downloaded on windows 11, didn't change any config, not sure if I was supposed to but on startup I get these 2 error messages. Are they safely ignorable like the pixbufloader errors?

**Comment by ouwou** [comment]
cookies and build number arent super critical, but it does help prevent you from getting banned by discord automatically from their crummy spam filters. that said, these two things shouldnt be failing. is there any chance discord is restricting your ip? that is if you go to https://discord.com/app does it load normally without something like a captcha? also if youre willing i can write a patch that should give us some more information as to whats wrong here

**Comment by ouwou** [comment]
well if the pixbuf error is just in the console and not its own popup window, then that is irrelevant and can be safely ignored. if you can confirm the cookie/build number fetch is still failing (and wasnt just some transient failure) i can try looking into it some more

**Comment by ouwou** [comment]
there was some undefined behavior i fixed recently which hopefully should have taken care of this. feel free to reopen if its still an issue on the latest master build
