### ISSUE TITLE
Feature request: QR code login

### ISSUE THREAD

**Issue by iAmInActions** [uowuo/abaddon#166]
Hello, I have been using this client for a while now and it works very well but the login procedure is rather annoying as it takes ages for the website to load on my G4 Powerbook (which is why I started using this in the first place) so I was wondering how plausible it would be to add an optional feature to log in via a QR code. The codes that Discords own website shows must be generated by the API somehow too so in theory there should be a way to generate them from this client too.

**Comment by ScarlettPPC** [comment]
I would love to see something like this. I've randomly had my token change before so this would make it a lot easier to log in again

**Comment by ouwou** [comment]
even though im not super into the idea in principle on second thought i figured it actually be a fun thing to have a go at anyways. my only real apprehension is ill have to bring in openssl and something to encode QR codes but that shouldnt be a big deal. itll be on the `remoteauth` branch whenever i push that; ill probably open a PR too

![image](https://github.com/uowuo/abaddon/assets/26526779/4b5dc9de-8f36-4c2a-a513-c28e99d2f3c2)

**Comment by ouwou** [comment]
still needs some finishing up but give the `remoteauth` branch a try. should hopefully work pretty simple and straight forward

**Comment by ouwou** [comment]
ill have it merged soon, but the branch was made after voice was merged into master so im not sure how thats possible 😹

**Comment by iAmInActions** [comment]
Thanks for the good news!
Unrelated, I'd like to help out with the project since I use it a lot and really like it but since I am not the best at programming I was wondering if you take donations.

**Comment by ouwou** [comment]
thanks, maybe ill figure something out in the future but id only really have a monero address right now 😹 so dw about it
