### ISSUE TITLE
Imported target "spdlog::spdlog" includes non-existent path

### ISSUE THREAD

**Issue by ScarlettPPC** [uowuo/abaddon#168]
Really cool to see that it supports voice chat now! Excited to try it but I get this error when I run cmake: 

-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "spdlog::spdlog" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

I have all of the dependencies installed

**Comment by ouwou** [comment]
looks like something on your end but from some googling perhaps a symbolic link on `/include` to point to `/usr/include` or equivalent would fix it. there might be a "better" way to fix it but unfortunately im not good enough at cmake to know what that solution would be

**Comment by ScarlettPPC** [comment]
Ah ok, where do I put the link?

**Comment by ouwou** [comment]
just do `ln -s /usr/include /include` i think

**Comment by ScarlettPPC** [comment]
That worked, thanks!
