### ISSUE TITLE
fatal error "fmt/core.h" missing

### ISSUE THREAD

**Issue by PATATAGAME554** [uowuo/abaddon#171]
here a screen with the complete error, how can this can be fixed/can you fix this?
![IMG_20230601_144759](https://github.com/uowuo/abaddon/assets/76092291/4de77183-7e7f-4ce2-9195-ead2c9e9c40e)

**Comment by ouwou** [comment]
can you try latest master?

**Comment by PATATAGAME554** [comment]
> can you try latest master?

sure, I'll try right now :)

**Comment by PATATAGAME554** [comment]
> can you try latest master?

now works fine, thanks :)
