### ISSUE TITLE
Client insta crashes when clicking on any direct message or channel on windows 11

### ISSUE THREAD

**Issue by PunchCakee** [uowuo/abaddon#172]
Hello, i've downloaded the latest build from the CI and this what happens when i try to open anything

```
C:\Users\faisal\Desktop\abaddon-MinSizeRel-f1fb241\bin>abaddon.exe
[2023-06-02 01:07:20.117] [audio] [info] Audio backend: WASAPI
[2023-06-02 01:07:20.158] [audio] [info] using Headphones (High Definition Audio Device) as playback device
[2023-06-02 01:07:20.160] [audio] [info] using Microphone (High Definition Audio Device) as capture device

(abaddon.exe:3488): Gtk-WARNING **: 01:07:20.270: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
Unknown event GUILD_AUDIT_LOG_ENTRY_CREATE
Unknown event GUILD_AUDIT_LOG_ENTRY_CREATE
GET /channels/480832693257502720/messages?limit=50
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Users\faisal\Desktop\abaddon-MinSizeRel-f1fb241\share\icons\Adwaita\16x16/status\image-missing.png: Error opening file C:\Users\faisal\Desktop\abaddon-MinSizeRel-f1fb241\share\icons\Adwaita\16x16\status\image-missing.png: No such file or directory (g-io-error-quark, 1)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Users\faisal\Desktop\abaddon-MinSizeRel-f1fb241\share\icons\Adwaita\16x16/status\image-missing.png: Error opening file C:\Users\faisal\Desktop\abaddon-MinSizeRel-f1fb241\share\icons\Adwaita\16x16\status\image-missing.png: No such file or directory (g-io-error-quark, 1)
```

**Comment by ouwou** [comment]
this is a weird one... im trying to figure it out (and i was able to replicate it in a weird way), but double check and make sure you extracted the zip properly and left the folder structure completely unmodified. also try `set PATH=` before `abaddon.exe` in the command line just to see if theres anything weird polluting the system environment

**Comment by PunchCakee** [comment]
> this is a weird one... im trying to figure it out (and i was able to replicate it in a weird way), but double check and make sure you extracted the zip properly and left the folder structure completely unmodified. also try `set PATH=` before `abaddon.exe` in the command line just to see if theres anything weird polluting the system environment

I just extracted it on desktop then double clicked the exe on bin

**Comment by PunchCakee** [comment]
update: i did what you asked and i still got the same error

**Comment by ouwou** [comment]
try adding the .png it's complaining about missing, drop it in `share\icons\Adwaita\16x16\status`. let me know if that works and if it doesnt crash then if there are any missing images (that is, you shouldnt actually be able to see this png anywhere)

https://raw.githubusercontent.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/27bc126a0d9f1a3ac46c6cd7ce2e6b9eea813127/gtk-nsis-pack/share/icons/Adwaita/16x16/status/image-missing.png

**Comment by PunchCakee** [comment]
> try adding the .png it's complaining about missing, drop it in `share\icons\Adwaita\16x16\status`. let me know if that works and if it doesnt crash then if there are any missing images (that is, you shouldnt actually be able to see this png anywhere)
> 
> https://raw.githubusercontent.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/27bc126a0d9f1a3ac46c6cd7ce2e6b9eea813127/gtk-nsis-pack/share/icons/Adwaita/16x16/status/image-missing.png

its still the same error even after adding it

**Comment by ouwou** [comment]
error is the same path with 16x16?

**Comment by PunchCakee** [comment]
> error is the same path with 16x16?

yes

**Comment by ouwou** [comment]
can you try replacing `share/icons/Adwaita/icon-theme.cache` with the version from [here](https://github.com/uowuo/abaddon/files/11640187/icon-theme.cache.zip) and also remove the image-missing.png i had you add? if that doesnt work try https://github.com/uowuo/abaddon/suites/13342082856/artifacts/729417956

**Comment by PunchCakee** [comment]
i works now!

**Comment by ouwou** [comment]
just to clarify did replacing the file with the one in the zip work or did you have to use the build i linked?

**Comment by PunchCakee** [comment]
> just to clarify did replacing the file with the one in the zip work or did you have to use the build i linked?

replacing the cache fixed it
