### ISSUE TITLE
Voice channels doesn't show up

### ISSUE THREAD

**Issue by hawl1** [uowuo/abaddon#175]
even though i installed the v.0.1.11 version

**Comment by ouwou** [comment]
did you download the zip from releases or did you build it yourself from master? this would be quite a strange bug so id suggest double checking to make sure ur on the latest. also make sure ur not looking at stages, cuz those wont show up yet

**Comment by hawl1** [comment]
i downloaded from the latest releases
and yes im not looking at stages

ouwou ***@***.***>, 12 Haz 2023 Pzt, 09:46 tarihinde şunu
yazdı:

**Comment by ouwou** [comment]
and you see "using ____ as playback device" in the console too? and no voice channels show up at all? (they have a little speaker icon and arrow). voice channels that are created while youre connected wont show up, but apart from that im not sure what the problem here could be

**Comment by hawl1** [comment]
wait it doesnt appear
lemme download it again
now it works sorry for my stupid

**Comment by ouwou** [comment]
thats okay 😹
