### ISSUE TITLE
[Feature Request] Trayer Icon?

### ISSUE THREAD

**Issue by formula-spectre** [uowuo/abaddon#184]
I think it would be neat to have a trayer icon, possibly so you can right click to toggle abaddon

**Comment by ouwou** [comment]
i think what you want already exists if you insert this into the settings, albeit no real icon exists yet

```
[gui]
hide_to_tray=true
```

**Comment by formula-spectre** [comment]
yep, thank you!

**Comment by Sohail-XD** [comment]
Dont know if this is the right place to ask but this setting doesnt work for me on arch linux hyprland with waybar tray.
