### ISSUE TITLE
[BUG] client crashes when closing a DM

### ISSUE THREAD

**Issue by cabiste69** [uowuo/abaddon#187]
when closing a DM using the abaddon client or another client (while abaddon is open) it crashes with this error

```
DELETE /channels/1068010237023502397
/usr/include/c++/13.1.1/optional:484: constexpr const _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() const [with _Tp = Snowflake; _Dp = std::_Optional_base<Snowflake, true, true>]: Assertion 'this->_M_is_engaged()' failed.
``` 

there's a core dump as well but i honestly don't know how to read that

**Comment by ouwou** [comment]
should be fixed let me know if theres still an issue

**Comment by cabiste69** [comment]
that was fast... I tested it and it works now, thanks a lot
