### ISSUE TITLE
nothing appearing after logging in

### ISSUE THREAD

**Issue by gitguette** [uowuo/abaddon#189]
when running abaddon after compiling it, i get a largely white screen with the options on top, after then copy-pasting the token using the guide from [github.com/Tyrrrz/DiscordChatExporter/issues/76#issuecomment-410067054](https://github.com/Tyrrrz/DiscordChatExporter/issues/76#issuecomment-410067054),then pressing connect, all that appears is what i presume to be a server notification symbol. if i put in a token i know to be incorrect, it simply rejects it

**Comment by gitguette** [comment]
also, the token does not persist after closing and re-opening. is this standard behavior?

**Comment by ouwou** [comment]
the white screen sounds like it cant find the resources, but you should have gotten a popup for that, make sure the res/res and res/css folders are copied/linked next to the compiled executable. as for the nothing appearing, could you send a screenshot? could be a case of the user guild_settings handling acting weird again but hard to tell from what you said

**Comment by gitguette** [comment]
![screenshot-07-07-2023.png](https://github.com/uowuo/abaddon/assets/109386903/da32b26c-48b5-4496-91b4-6f7b564e8cff)

**Comment by gitguette** [comment]
copying the res/css and res/res makes most of it work, but some symbols before channels are failing to display, instead showing a square with a code inside of it
