### ISSUE TITLE
the stock emoji option doesn't persist

### ISSUE THREAD

**Issue by gitguette** [uowuo/abaddon#191]
after editing abaddon.ini, the stock_emojis option resets to false when starting abaddon

**Comment by ouwou** [comment]
make sure abaddon is closed when you edit the file, otherwise it will overwrite the changes. if you are sure its closed can you test if it affects any other options? also im assuming you are on windows since false is the default only on windows, correct me if you arent

**Comment by gitguette** [comment]
i guess i had it open, as it's no longer an issue
