### ISSUE TITLE
"The audio engine could not be initialized!" (For those without working audio drivers)

### ISSUE THREAD

**Issue by flleeppyy** [uowuo/abaddon#203]
Hiya, I use a Samsung Chromebook 4+ that has custom firmware so I can boot windows 10. Unfortunatly, audio does not work. There are no free audio drivers for my this Chromebook (there is a paid one but I do not have that kind of money) so I either have to use Bluetooth audio or just stick to no sound. I use this for school so sound is not that important.

I'd like to be able to use abaddon without audio and just get visual notifications.
![image](https://github.com/uowuo/abaddon/assets/18307183/83ce6fb5-45ed-4e80-a7e1-b53b1fd4c551)

```
[2023-08-08 10:54:05.709] [audio] [info] Audio backend: WASAPI
[2023-08-08 10:54:05.719] [audio] [warning] No default playback device found
[2023-08-08 10:54:05.719] [audio] [warning] No default capture device found
[2023-08-08 10:54:05.722] [audio] [error] failed to initialize playback device
```

Is it possible to just warn the user that features like audio notifications and voice chats won't work without an audio device, instead of just exiting?

**Comment by flleeppyy** [comment]
I've been able to mitigate this issue by just installing Voicemeeter, but that shouldn't be a viable work around, especially if the audio engine is actually disabled for the user for any reason.

**Comment by ouwou** [comment]
can you try a build from the latest master branch? it should only generate a warning but still let you launch. notifications arent implemented on windows btw (gio doesnt provide a backend and libraries like wintoast dont work because mingw64 doesnt have the necessary header files 🥴)

**Comment by flleeppyy** [comment]
Works pretty good! Also for notifications, maybe you could do what last.fm does when it detects you playing a new song, creates a non-draggable, no header no border blah blah, window in the bottom right, then fades out after a while, or after you open abaddon
