### ISSUE TITLE
Stuck on "Getting connection info..."

### ISSUE THREAD

**Issue by flleeppyy** [uowuo/abaddon#204]
I've been at this screen for a while now and I'm not expecting it to change any time soon.
Regular Discord web app (Stable) and desktop app (Canary) works fine for me.
![image](https://github.com/uowuo/abaddon/assets/18307183/9ebf268d-99a5-4bd2-a933-6f26daa9ded3)

Not seeing anything interesting in console either. Is there any command-line options I can add to get more debug info about what could be going on?
```
[2023-08-08 11:01:54.870] [audio] [info] Audio backend: WASAPI
[2023-08-08 11:01:55.149] [audio] [info] using VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO) as playback device
[2023-08-08 11:01:55.159] [audio] [info] using VoiceMeeter Aux Output (VB-Audio VoiceMeeter AUX VAIO) as capture device

(abaddon.exe:8): Gtk-WARNING **: 11:01:55.525: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

I'm on Windows 10 22H2 Build 19045

**Comment by ouwou** [comment]
`set SPDLOG_LEVEL=trace` in command line will enable all debug logs, but theres no extra logging that will help here. i think the underlying requests are hanging for some reason. ill probably add a timeout either way but if you apply this patch CURL should spew connection details to console which might help show whats going wrong

```diff
diff --git a/src/startup.cpp b/src/startup.cpp
index 06d6402..3547c3c 100644
--- a/src/startup.cpp
+++ b/src/startup.cpp
@@ -48,6 +48,7 @@ std::optional<uint32_t> GetBuildNumberFromJSURL(const Glib::ustring &url, const
     req.set_user_agent(Abaddon::Get().GetSettings().UserAgent);
 
     curl_easy_setopt(req.get_curl(), CURLOPT_COOKIE, cookie.c_str());
+    curl_easy_setopt(req.get_curl(), CURLOPT_VERBOSE, 1L);
 
     auto res = req.execute();
     if (res.error) return {};
@@ -75,6 +76,7 @@ std::pair<std::optional<std::string>, std::string> GetCookieTask() {
     req.set_user_agent(Abaddon::Get().GetSettings().UserAgent);
 
     curl_easy_setopt(req.get_curl(), CURLOPT_COOKIEFILE, "");
+    curl_easy_setopt(req.get_curl(), CURLOPT_VERBOSE, 1L);
 
     auto res = req.execute();
     if (res.error) return {};
```

**Comment by flleeppyy** [comment]
Somewhere in between the release build and master branch build the issue doesn't occur. So I'm not sure where it got fixed.

**Comment by Chik3r** [comment]
It seems to have been fixed in one of these commits from running the CI builds (it gets stuck on `finalize login` but works in `show status, error when captcha required`)
![image](https://github.com/uowuo/abaddon/assets/31808958/74ffe8b2-732a-4df7-b80a-19977a63bed3)

**Comment by ouwou** [comment]
is that consistent behavior, like if u try multiple times? none of those commits touch the code in question, nor do any between 0.1.11 and master (except a [UB fix](https://github.com/uowuo/abaddon/commit/22025c2f0d13e4a4179cc7bc88a854fc4ab2105e)). if somehow it really has stopped being an issue on the latest master i guess we can close this then.

**Comment by flleeppyy** [comment]
> is that consistent behavior, like if u try multiple times? none of those commits touch the code in question, nor do any between 0.1.11 and master (except a [UB fix](https://github.com/uowuo/abaddon/commit/22025c2f0d13e4a4179cc7bc88a854fc4ab2105e)). if somehow it really has stopped being an issue on the latest master i guess we can close this then.


it uh, could have been the fact that at the time my laptop had not been restarted in 74 days...
oops

**Comment by flleeppyy** [comment]
let's leave this at user error for now until someone gets this error again lol.
