### ISSUE TITLE
[Bug] user list is broken

### ISSUE THREAD

**Issue by TheMorc** [uowuo/abaddon#213]
guys at Discord must've been doing something ***really necessary*** again because they broke the user list to pieces
<img width="147" alt="image" src="https://github.com/uowuo/abaddon/assets/13377926/87250566-99a4-4131-b7de-157e39410eb7">

**Comment by ouwou** [comment]
is this on latest master? i think i fixed this the other night. the relevant log entry would be something about field "count" not found

**Comment by TheMorc** [comment]
> is this on latest master? i think i fixed this the other night. the relevant log entry would be something about field "count" not found

you are right lol 🙃
