### ISSUE TITLE
Add the ability to show channel list on a separate sidebar (like the official Discord client)

### ISSUE THREAD

**Issue by yusdacra** [uowuo/abaddon#221]
This would be really nice (for me anyway) since I find the current UI really tiring to use with all the scrolling that I have to do if I want to find a channel.

**Comment by tawnylure** [comment]
Preach!
The UI gets suprt cluttered super fast, this would legit resolve that issue.

**Comment by yusdacra** [comment]
I'm not really sure what would be a better UI/UX unfortunately. This is unrelated to this but, being able to pin channels to somewhere always reachable (like the guild list) might also help with some issues.

**Comment by jernejs** [comment]
A killer feature for me would be being able to favorite channels from different guilds ("servers") – I'm in something like 30 guilds, and only interested in a few channels from each. In Ripcord, I had these channels pinned in Favorites.

**Comment by ouwou** [comment]
would it work if you had the classic discord-style guild list with the icons on the left and the channel list that exists now on the right with the channel list only showing the selected guild? or in other words is there anything wrong with the channel list that exists now apart from the fact its not just the desired guild thats visible? (reusing the widget would make my life a lot easier)

**Comment by jernejs** [comment]
For my suggestion (favorites), the easiest would be to just add a virtual Favorites guild to the list, and let me pin channels from different guilds in there (you'd need to add the guild icon in front of the channel name though, since a ton of guilds use #general channel).
I actually prefer how Abaddon shows the guilds and channels over Discord, since it lets me quickly move between channels on different guilds (saves some mouse clicking).

**Comment by ouwou** [comment]
not sure when itll be done but you can take a peek at #242 to see the progress. right now its extremely basic and kinda buggy but im working on it

**Comment by ouwou** [comment]
been working on it more lately. id be open to some feedback as far as functionality but also appearance (even tho i know it still needs some tweaking). `classic-channels` branch, or [windows download](https://github.com/uowuo/abaddon/actions/runs/7457237432/artifacts/1155947362). i know we like favorites but thatll come separately after this is done

**Comment by 32bitx64bit** [comment]
Can't wait for it to be available so I can compile it.

**Comment by ouwou** [comment]
> Can't wait for it to be available so I can compile it.

well you can try compiling it from the right branch now if you want

**Comment by 32bitx64bit** [comment]
> > Can't wait for it to be available so I can compile it.
> 
> well you can try compiling it from the right branch now if you want

Exactly how? I'm not really in the know how's of Github and how to git a branch of something.

**Comment by 32bitx64bit** [comment]
> > > Can't wait for it to be available so I can compile it.
> > 
> > 
> > well you can try compiling it from the right branch now if you want
> 
> Exactly how? I'm not really in the know how's of Github and how to git a branch of something.
> 
> Edit figured it out. Heres the command for anyone looking to do the same. git clone --branch classic-channels https://github.com/uowuo/abaddon --recurse-submodules="subprojects" && cd abaddon

Progress looking solid.
Like it a lot more than the previous way. Just makes it so much more organized! 
Though would be nice having the sidebar just be invisible. or super tiny.

**Comment by ouwou** [comment]
>  Though would be nice having the sidebar just be invisible. or super tiny.

could you elaborate? not sure what u mean

**Comment by 32bitx64bit** [comment]
> > Though would be nice having the sidebar just be invisible. or super tiny.
> 
> could you elaborate? not sure what u mean
![raw](https://github.com/uowuo/abaddon/assets/86190528/3f22fd7b-7cbe-425e-88b8-99630531217a)

The scrollbar.

**Comment by ouwou** [comment]
it should be hidden unless you have your mouse in the scroll region. if you want it to never show up, i can add an option for that (and in that case, do you want the option for just the server icons, or channel list too?). and aside from visibility, its appearance is controlled by your theme

**Comment by 32bitx64bit** [comment]
> it should be hidden unless you have your mouse in the scroll region. if you want it to never show up, i can add an option for that (and in that case, do you want the option for just the server icons, or channel list too?). and aside from visibility, its appearance is controlled by your theme

A option would be nice to disable the scrollbar. :D

**Comment by jernejs** [comment]
I'd like the opposite – the scrollbar should be always visible.

**Comment by ouwou** [comment]
> A option would be nice to disable the scrollbar. :D

ok done you can do
```ini
[style]
classic_guild_scroll_policy=never
classic_channel_scroll_policy=never
```
(or "always" or "automatic" which is default)

**Comment by 32bitx64bit** [comment]
Seems like when I recompile, the sidebar returns to what it used to be. Might wanna look into that.

**Comment by ouwou** [comment]
> Also seems that when you disable the scrollbar, scrolling is just disabled entirely. Just wanted the bar hidden, not scrolling. Just to clear things up. Or its a bug, idk which tbh.

oh. yeah. im not smart. i forgot thats how scrolling works in gtk (not sure how i didnt catch that). time to revert it and ill think of something else

**Comment by ouwou** [comment]
i think youll just have to use css to hide the scroll bars, try this (needs latest commit)

```css
.channel-browser-pane scrollbar {
	border: none;
}

.channel-browser-pane scrollbar slider {
	border: none;
	margin: 0;
	min-width: 0;
	min-height: 0;
}
```

**Comment by 32bitx64bit** [comment]
> i think youll just have to use css to hide the scroll bars, try this (needs latest commit)
> 
> ```css
> .channel-browser-pane scrollbar {
> 	border: none;
> }
> 
> .channel-browser-pane scrollbar slider {
> 	border: none;
> 	margin: 0;
> 	min-width: 0;
> 	min-height: 0;
> }
> ```

Hi, sadly my discord account is currently disabled. I'll try this asap. 
But yk, discord support slow.

**Comment by 32bitx64bit** [comment]
> > i think youll just have to use css to hide the scroll bars, try this (needs latest commit)
> > ```css
> > .channel-browser-pane scrollbar {
> > 	border: none;
> > }
> > 
> > .channel-browser-pane scrollbar slider {
> > 	border: none;
> > 	margin: 0;
> > 	min-width: 0;
> > 	min-height: 0;
> > }
> > ```
> 
> Hi, sadly my discord account is currently disabled. I'll try this asap. But yk, discord support slow.

This bit of code doesn't work

**Comment by 32bitx64bit** [comment]
Also a little update, ordering just isn't correct. nothing is in order properly. ITs all random.

**Comment by ouwou** [comment]
> Also a little update, ordering just isn't correct. nothing is in order properly. ITs all random.

i think i fixed that yesterday. try on the newest commit



> This bit of code doesn't work

also check if this is still a problem on the newest commit. i made it a default (but just for the server list. if it works for the server list maybe ill add it to the channel list too)

**Comment by 32bitx64bit** [comment]
> > Also a little update, ordering just isn't correct. nothing is in order properly. ITs all random.
> 
> i think i fixed that yesterday. try on the newest commit
> 
> > This bit of code doesn't work
> 
> also check if this is still a problem on the newest commit. i made it a default (but just for the server list. if it works for the server list maybe ill add it to the channel list too)

I just compiled it today, the fix didn't work.

And the sidebar is indeed hide for a little, but if u hover it appears, not that big of a isuse.

**Comment by ouwou** [comment]
i really wanna merge this already and i think its basically ready so if theres any last minute bugs or suggestions i would like to hear them
@32bitx64bit also maybe you can see if you can replicate the ordering issue. it works fine for me. only issue i have heard from someone is in the private messages section but i cant replicate that either
