### ISSUE TITLE
[bug] Some pictures are not displayed

### ISSUE THREAD

**Issue by glitch65** [uowuo/abaddon#229]
pictures and screenshots that were taken from the phone are not displayed

**Comment by ouwou** [comment]
can you be more specific and/or show me a screenshot of what you mean? im not sure what "taken from the phone" means

**Comment by ouwou** [comment]
can you right click the empty image and click "copy link" and send it here so i can see if i can replicate it?

**Comment by ouwou** [comment]
image seems to load fine on my end both pasting and reuploading it myself. do you see anything in the console like "(url here) is null"? also what OS?

**Comment by jernejs** [comment]
I noticed the same problem on Windows 11 22H2, eg. with image https://media.discordapp.net/attachments/548641893760630824/1155515610541850705/38120a96-4c71-4552-ab28-969661549f31.png?width=722&height=777
There's nothing useful in the console:
![image](https://github.com/uowuo/abaddon/assets/1800143/d7fd04e2-2e8a-4ed1-9f98-db0affdeaddd)

**Comment by ouwou** [comment]
cant seem to replicate with either of those :\ maybe you can post it directly in the discord server?

**Comment by jernejs** [comment]
Which server is that?

**Comment by ouwou** [comment]
> Which server is that?

the one in the readme, https://discord.gg/wkCU3vuzG5

**Comment by jernejs** [comment]
Posted an example in #general .
