### ISSUE TITLE
No way to open a new DM from friends list?

### ISSUE THREAD

**Issue by Drake356** [uowuo/abaddon#233]
Am I missing something or is all we can do with the friends list is remove people, if I don't share a server or see someone elsewhere to open their profile I can't start a DM. I also don't see any way to start a group DM.

**Comment by ouwou** [comment]
you used to be able to start new DMs, but doing that was by far one of the most risky things in term of getting automatically flagged and disabled by discord so i removed it. maybe ill reevaluate that at some point but for now youll have to use the official client or have other people start DMs for you

**Comment by Drake356** [comment]
Sus
