### ISSUE TITLE
[Feature request] Support for being moved in VCs

### ISSUE THREAD

**Issue by justsam7** [uowuo/abaddon#234]
Support for being able to get moved to a different VC without having to manually connect to it again. (Being dragged by other users (or bots) for instance). Useful for some games that use discord vcs as a queueing system

**Comment by ouwou** [comment]
being moved should work just fine. are you sure its not working? i know the voice window will only pop up sometimes but apart from that it should behave as youd expect

**Comment by ouwou** [comment]
let me know if still an issue
