### ISSUE TITLE
Microphone audio coming out only on the left side for other users

### ISSUE THREAD

**Issue by riomccloud** [uowuo/abaddon#238]
I noticed that the audio from my microphone only comes from the left side to the other users on the call. This only happens with abaddon. My lavalier microphone is generic. I tried to change options in the call but I couldn't resolve it.

**Comment by ouwou** [comment]
which OS and audio backend (printed to console)?

**Comment by riomccloud** [comment]
OS: Windows 10 21H2 (amd64)
Audio backend: WASAPI

**Comment by de-katze** [comment]
That's strange, discord is supposed to be mono only.

**Comment by ouwou** [comment]
ill try making a small standalone program thatll echo back your microphone to see if its a miniaudio issue or a me issue

> That's strange, discord is supposed to be mono only.

discord will mix your audio to mono before encoding it, but opus is a strictly stereo codec so you can send stereo audio. i guess discord doesnt mix audio to mono after decoding

**Comment by ouwou** [comment]
can you try this? this will simply echo back your microphone input when you open it, so it should help determine if the problem is a result of the library or me making a mistake using it. if it sounds wrong, also send the output of the exe

[audio test.zip](https://github.com/uowuo/abaddon/files/13035126/audio.test.zip)

**Comment by riomccloud** [comment]
Here it is:
[audio-log.txt](https://github.com/uowuo/abaddon/files/13047714/audio-log.txt)

**Comment by ouwou** [comment]
and just to confirm youre hearing the same issue with that where audio is playing back only through the left channel?

**Comment by riomccloud** [comment]
Yep.

**Comment by ouwou** [comment]
and just to make sure its a miniaudio issue and not a microphone issue can you record yourself on https://mictests.com/ and play it back (or any other software that doesnt do any mixing/channel conversion) and also check the displayed channel count on the left? the other software you used might have mixed to mono so itd be helpful to rule that out. in meantime ill ask the miniaudio dev about this

**Comment by riomccloud** [comment]
I tested it and... really the audio only comes from the left. I never imagined it could be mixing...
Ok, not miniaudio's fault, but is there a way to force mixing audio on both channels, with Abaddon or for the entire Windows system?

**Comment by ouwou** [comment]
i can add a force mono option, but as a workaround you can go to your sound control panel and set the microphone to be mono

**Comment by ouwou** [comment]
you can enable the "Mix Mono" option in the voice window now
