### ISSUE TITLE
General Suggestions ~~Local WS server.~~

### ISSUE THREAD

**Issue by wont-stream** [uowuo/abaddon#239]
The official client has a local websocket server that the website uses to communicate with the client.
For example if you have ever opened a discord invite in the browser with discord open, you'll notice it opens up the client to the top with the invite prompt.
It's also how games and other 3rd party programs set the users presence (most of the time it uses discords local ipc as the ws is locked to certified applications)

A small implementation exist made in nodejs at https://github.com/OpenAsar/arrpc

**Comment by de-katze** [comment]
and just because I felt like it here's a highly opinionized "logo" I threw together
![abaddon](https://github.com/uowuo/abaddon/assets/143244075/8c2dd62c-71c9-4bf5-af11-9a1b7d528b2f)

**Comment by de-katze** [comment]
Alright, I was looking through `abaddon-MinSizeRel-e3ad25f\bin\res` and it doesn't quite look like there's a logo for everything, missing about seven icons, and may I suggest using SVGs for all of the assets?

**Comment by de-katze** [comment]
Uhh one more thing, seems like you are missing 8~ badges. and it seems as some of them are outdated compared to the new looks

**Comment by de-katze** [comment]
oh and uh
maybe a tray icon?
I know its kinda difficult since you need to support all the platforms but it would be a nice QOL thing

**Comment by de-katze** [comment]
![image](https://github.com/uowuo/abaddon/assets/143244075/10bd48df-1fc6-4ff0-913b-40534b8273c6)
#236 just found this

**Comment by de-katze** [comment]
The ability to hide the console to the tray for example would be nice

**Comment by ouwou** [comment]
> Alright, I was looking through `abaddon-MinSizeRel-e3ad25f\bin\res` and it doesn't quite look like there's a logo for everything, missing about seven icons, and may I suggest using SVGs for all of the assets?

for profile connections? i guess thats not surprising. i didnt use SVG cuz ive had bad experiences with getting them to work consistently in GTK

> Uhh one more thing, seems like you are missing 8~ badges. and it seems as some of them are outdated compared to the new looks

ill give it a look

> ![image](https://user-images.githubusercontent.com/143244075/276049653-10bd48df-1fc6-4ff0-913b-40534b8273c6.png) #236 just found this

where does this occur? im probably escaping it somewhere it doesnt need to be

> The ability to hide the console to the tray for example would be nice

theres a setting for that (`[windows] hide_console=true`). guess i forgot to document it

**Comment by de-katze** [comment]
> where does this occur? im probably escaping it somewhere it doesnt need to be

appears in chat and the profile popout
those are the only places I've come across

**Comment by ouwou** [comment]
> appears in chat and the profile popout those are the only places I've come across

could you take a screenshot in context so i can see where exactly? im struggling to replicate it

**Comment by de-katze** [comment]
Hm, currently I have moved to Linux and I can only recreate the issue in chat. ![image](https://github.com/uowuo/abaddon/assets/143244075/f7ee9c0f-42ce-4292-adb9-fa9dd2325327)

**Comment by wont-stream** [comment]
@ouwou Hello, it's been quite a few months now, and it seems you've gotten all figured out.
Is this safe to close?

**Comment by ouwou** [comment]
yeah ill just close this cuz its kinda all over the place. if theres anything specific still missing u can open a new one if u want
