### ISSUE TITLE
[Enhancement] Respect system GTK theme

### ISSUE THREAD

**Issue by aaronliu0130** [uowuo/abaddon#245]
- [x] channel list text colors are extremely broken
- [x] chat input box (way too small, clips attachment icon)
- [x] hover effects look bad/should probably be disabled (might be a theme issue?)
- [x] attachment boxes are unpadded
- [x] embeds
- [x] reactions
- [ ] css color stuff for renderer
- [ ] ~~ScrolledWindow backgrounds~~
- [x] chat input size is weird
- [x] link colors
- [x] reaction border
- [x] connection boxes
- [x] attachment progress bar

You can test this on any system including Windows. See https://stackoverflow.com/questions/36464010/change-gtk3-look-on-windows

**Comment by ouwou** [comment]
a good starting point is to make it look good under the default adwaita/dark adwaita. i edited the issue with a checklist of some stuff that stood out to me right away.
ill probably make all the css changes within `css/bare.css` (the intention behind it was to be the "minimal" needed css). so for now the respect-the-theme mode is to use `css/bare.css` as main and make `css/application-low-priority.css` empty. i think maybe a good end goal is to end up renaming `css/bare.css` to main and the current theming could just be a gtk3 theme packaged in alongside the binary

and of course if anything else looks broken or ugly under the bare css im open to feedback

**Comment by aaronliu0130** [comment]
Sounds good as long as I don’t need to remove the bundled theme to use the system theme every update

**Comment by ouwou** [comment]
okay ive been doing stuff in the `theming` branch. main.css has been updated to be mostly padding and whatnot and it should look pretty good now under the system GTK theme. theres still some minor stuff that needs tweaking
but at this point id be interested in any feedback as to the appearance (positive or negative, and especially if something looks broken)

**Comment by aaronliu0130** [comment]
![image](https://github.com/uowuo/abaddon/assets/11874211/b001eaea-3407-49d1-b88f-c49129c1ee1c)
Yay, it is native!1!! Some things though:
Left and right sidebars should probably be "shaded" like how file managers shade the left sidebar? IDK what class that is 
<details>
<summary>Nautilus and Caja, file managers</summary>

![image](https://github.com/uowuo/abaddon/assets/11874211/e3131d43-8ad3-4b4b-8b06-68519662f1d5)
![image](https://github.com/uowuo/abaddon/assets/11874211/043ff490-fb58-449f-92b8-a063cb558ffa)

</details>

Also, the text input box is too large, and the send button is on the left for some reason? Is that intended? I also can't find a way to X out of replying and send a normal message instead and I can't see whether a reply has pinged a user.

**Comment by aaronliu0130** [comment]
![image](https://github.com/uowuo/abaddon/assets/11874211/989d994f-6af1-438f-9e5d-728924217a4a)
Links have a weird color, the channel selector isn't really separated from chat, and numbers emojis in names don't seem to render right (the 8(square)ron Liu on 8(square) is supposed to look like 8️⃣ron Liu on 8️⃣)

**Comment by ouwou** [comment]
> Left and right sidebars should probably be "shaded" like how file managers shade the left sidebar

i think thats because theyre ScrolledWindows. i agree tho so ill try to figure that out

> the text input box is too large

also seems like a weird theme issue but hopefully something i can try and fix

> the send button is on the left for some reason

that opens the file picker for adding attachments. doesnt really look like it because of your icon theme, im not sure if theres anything better than `document-send` (which to be fair "Should be an arrow pointing up and away from a hard disk.")

> a way to X out of replying

hit escape. a clickable button like discords isnt a bad idea tho

> can't see whether a reply has pinged a user

if you mean replies you send the answer is yes its set to ping whoever youre replying to. i might add a toggle for that at the same time i do the click to stop replying thing

> Being able to drag the sidebars' border closer to the center to make them horizontally wider or narrower would also be nice

could you explain this more cuz i dont really understand what you mean

> Links have a weird color

links dont really exist in GTK, so i have to implement them myself. i might have found a way to pick up the theme color for it though so ill try that out (and change the fallback color while im at it cuz it is weird)

> numbers emojis in names don't seem to render right

try disabling the custom emoji handling (`[gui] stock_emojis=false`). im considering making it false by default anyways its honestly a bit of a relic from before i figured out how to get the font to show color emojis properly on win32

> reactions and integration box borders should perhaps be a gtk theme color instead of black, not sure which tho

ill keep that in mind. i think the integration boxes look kinda out of place so ill probably switch that up entirely at some point

**Comment by ouwou** [comment]
ok so the text input box seems to be too big if your theme defines `min-height` for `scrollbar.vertical` to be too high (at least in my case thats whats going wrong). i could just disable scroll bars but that seems a bit wrong, so not too sure what to do about this

**Comment by ouwou** [comment]
> ok so the text input box seems to be too big if your theme defines `min-height` for `scrollbar.vertical` to be too high (at least in my case thats whats going wrong). i could just disable scroll bars but that seems a bit wrong, so not too sure what to do about this

figured it out. just overrode that property so text input height should be fine now

**Comment by aaronliu0130** [comment]
> im not sure if theres anything better than `document-send` (which to be fair "Should be an arrow pointing up and away from a hard disk.")

Well, that's semantically very incorrect, and even GNOME doesn't obey that "should". While it's a status icon, not an action icon, maybe `mail-attachment` could work?

> if you mean replies you send the answer is yes its set to ping whoever youre replying to.

I meant seeing if other users' replies ping or not. In Discord's client, there's a subtle distinction as to whether a reply pings. If it pings, there'll be an @ in front of the replied user's name. If not, there won't.

![image](https://github.com/uowuo/abaddon/assets/11874211/d624a02e-94b4-4771-a1f8-95d72c8fda60)

> Being able to drag the sidebars' border

![Peek 2023-12-03 14-38](https://github.com/uowuo/abaddon/assets/11874211/dcb2cf3c-6e7d-4e9b-9986-77397fa18ca0)

> try disabling the custom emoji handling

I put the abaddon.ini in the exec's folder and it said it couldn't find the settings file before forgetting my token

**Comment by ouwou** [comment]
its implemented using Gtk.Paned so it should work? not sure what the issue would be
![abaddon_Iv1ITjQ9kW](https://github.com/uowuo/abaddon/assets/26526779/6fe0d38c-4dbf-4118-a8f2-403fcab45860)

**Comment by aaronliu0130** [comment]
Huh... yes it does work, idk what i was on

**Comment by MasterSlenderTR** [comment]
Hello, I'm using the native win32 theme but I seem to have a blue hover color even though my Windows theme uses purple everywhere, how can I set that blue to purple?
![Untitled](https://github.com/uowuo/abaddon/assets/50411937/a8d21fea-ebe1-472a-a3cd-5dbdcb79df65)

**Comment by ouwou** [comment]
thats probably a shortcoming in the theme, but you can try editing main.css and adding

```css
treeview:selected {
    background-color: somecolorhere;
}
```

im not sure how gtk is getting the accent color and i dont use vista so i cant really test that, but you can try the `-gtk-win32-color` colors listed here: https://github.com/GNOME/gtk/blob/3.24.38/gtk/theme/win32/gtk-win32-base.css

**Comment by MasterSlenderTR** [comment]
It's Win7 with Vista style.

**Comment by MasterSlenderTR** [comment]
Anyways thanks for your help, I was able to make it purple with the code you gave me. 
![image](https://github.com/uowuo/abaddon/assets/50411937/b674c46b-8afa-46c6-885a-74a65f94ea94)

**Comment by MasterSlenderTR** [comment]
how can I make text selection color purple as well?
![image](https://github.com/uowuo/abaddon/assets/50411937/85f3ccfd-15f3-4486-afee-f5f72f9c71d3)
