### ISSUE TITLE
Ability to add alt text to attachments

### ISSUE THREAD

**Issue by RUvlad1** [uowuo/abaddon#253]
Not really commonly used by most Discord users, but would be very much preferred to have the option considering it's an accessibility setting

Discord's version for reference:

![image](https://github.com/uowuo/abaddon/assets/60317461/3b96aee5-dd39-4a78-99c4-0daddc6da152)

![image](https://github.com/uowuo/abaddon/assets/60317461/e63ddaa2-0a98-4b4b-bcae-940e92a9b69f)

**Comment by ouwou** [comment]
added the ability to see alt text by hovering over the image. lemme know if any issues
