### ISSUE TITLE
Is there a zoom feature?

### ISSUE THREAD

**Issue by kars0n777** [uowuo/abaddon#254]
I was wondering if there is a way to zoom into the app since the text is tiny for me. I was wondering if there is a way to use the custom css or config file to change the font size. 

I wish that CTRL + "+" and CTRL + "-" just came out of the box as defaults for zoom, but if you know how to zoom please let me know.

**Comment by ouwou** [comment]
two options:
edit the css with
```css
* { font-size: 125%; }
```
(obviously use whatever % you like)
or (probably the best way):
edit the .ini
```
[gui]
font_scale=1.25
```

**Comment by kars0n777** [comment]
Thank you, I think this should be in the readme, as zoom is a big feature.

**Comment by ouwou** [comment]
`font_scale` is mentioned, albeit way at the bottom. usually gtk is supposed to handle scaling too (i think?)
