### ISSUE TITLE
Clicking a link opens an "Internet Explorer 11 is no longer supported" pop up

### ISSUE THREAD

**Issue by jerdftw** [uowuo/abaddon#255]
Clicking any link inside the client on windows will show this pop-up.
![image](https://github.com/uowuo/abaddon/assets/49598507/84ae19da-7237-47e5-a446-38877d27e9f1)

**Comment by ouwou** [comment]
sounds like a gtk/config issue. does this happen with any other applications or gtk3 applications?

**Comment by jerdftw** [comment]
This only seems to happen with this app, because using any other gtk application (HexChat in my case) is able to open links just fine.

**Comment by ouwou** [comment]
can you try changing your default browser to something else and then back? if that doesnt fix it then i can add a workaround for windows

**Comment by jerdftw** [comment]
It turns out that I didn't have my default browser set, and that's why i was getting that prompt.
