### ISSUE TITLE
How can i get these themes?

### ISSUE THREAD

**Issue by RF7391** [uowuo/abaddon#264]
![image](https://github.com/uowuo/abaddon/assets/156833337/56630e8d-8bfe-472b-b4c0-36b61c410583)
![image](https://github.com/uowuo/abaddon/assets/156833337/60a13c05-0b4e-423c-b682-8da9f398eb6a)

how can i get these themes on abaddon? (im on windows)

**Comment by ouwou** [comment]
#1 is redmond97 digital cde: https://www.gnome-look.org/p/1313764
#2 is bottleglass dark: https://www.gnome-look.org/p/1467087

put the theme in the `share/themes` folder

edit `etc/gtk-3.0/settings.ini` and replace `gtk-theme-name` with the folder name

**Comment by RF7391** [comment]
share/themes folder does not exist,
as well as etc/gtk-3.0/settings.ini does not exist,
where do i find the ini file and all?

**Comment by ouwou** [comment]
> share/themes folder does not exist, as well as etc/gtk-3.0/settings.ini does not exist, where do i find the ini file and all?

which OS?

**Comment by RF7391** [comment]
windows 10

**Comment by ouwou** [comment]
use the latest master build: https://nightly.link/uowuo/abaddon/workflows/ci/master/build-windows-msys2-MinSizeRel.zip
you will need to create etc/gtk-3.0/settings.ini yourself. but the etc folder will already exist

**Comment by RF7391** [comment]
Yep it worked, ty
