### ISSUE TITLE
Crash on sending messages

### ISSUE THREAD

**Issue by K0l0rek** [uowuo/abaddon#27]
if click [enter] in dm with no text  yours app crash
the same if you spam in dm's multiple times like.
a
a
a
b
b
b
...
And using discord token in this discord wrapper , orginal one log me off

**Comment by ouwou** [comment]
you shouldn't be able to send empty messages now. i couldnt replicate a crash when spamming messages but i suspect that wont happen anymore, reopen this issue if it still crashes the same way

as far as the other comment i dont think thats something i can control (if i understood you correctly) its just something discord does sometimes
