### ISSUE TITLE
BUG: Token not fetched from INI file

### ISSUE THREAD

**Issue by MIvanchev** [uowuo/abaddon#270]
I am running with the following config

```
# Abaddon config

[discord]
keychain=false
token=<token>
autoconnect=true

[gui]
font_scale=1.4
```

And only the font scale is applied. Everything else just seems to be ignored.

**Comment by ouwou** [comment]
are you using latest release or master? the keychain setting hasnt made it to a release version yet

**Comment by MIvanchev** [comment]
The latest release :)

**Comment by ouwou** [comment]
well, let me know if for some reason it doesnt work on master. im trying to get a release out soon, just trying to finish up the last feature i wanna get in there :P
