### ISSUE TITLE
Token issue

### ISSUE THREAD

**Issue by r3k2** [uowuo/abaddon#274]
Hello, foremost, thank you! <3 I really want to make this my first choice because of the voice support, as of now I have been using discordo because I love TUI's and vim keys and webcord for voice, so abaddon has great potential! To only have to use one client that is non-electron big plus.
But as of now, I have some issues:
- token I have to add it every time, it does not safe :( 
- sometimes (same token) says is not valid, but other times it works. :shrug: 
- discordo has it in a way we can just log in as normal, can't we do that here?
- voice works, but not all the time.

My system:
- Arch GNU/Linux
- wayland/sway
- pipewire 

Thank you again.

**Comment by ouwou** [comment]
if your token doesnt save its probably because you dont have a keyring installed like gnome-keyring or kwallet (or anything supporting the Secret Service API). if you do have one of those installed then that sounds like a bug
so you can either install such a service or alternatively store it in plaintext in abaddon.ini which you can do by adding
```
[discord]
keychain=false
```

what issues do you have with voice?

**Comment by Doty1154** [comment]
I'm also on Arch(specifically cachyos) on the latest packages, with kwallet (specifically kde desktop enviroment, with packages kwalletmanager,kwallet-pam,kwallet5,signon-kwallet-extension)
When i attempt to sign in with a qr code i get a error saying the token is invalid, however when i remove the keyring support i'm able to sign in successfully.

**Comment by ouwou** [comment]
> When i attempt to sign in with a qr code i get a error saying the token is invalid, however when i remove the keyring support i'm able to sign in successfully.

that is interesting. so ur saying if you scan the QR code with keychain enabled, it gives you "discord rejected your token" immediately? and if keychain is disabled, it logs in fine? if you manually set a token in the set token dialog and connect, does that work with and without keychain enabled? the code paths for what happens after getting the token should be identical between QR code and manual entry

**Comment by Doty1154** [comment]
i've not tried manually inputing the login token, what's the recommended method for obtaining the token and what format does abaddon want the key to be in.

**Comment by ouwou** [comment]
oh also make sure you are on the latest master. i doubt itll change anything if you are only on the latest release but you never know

**Comment by ouwou** [comment]
reopen if still an issue
