### ISSUE TITLE
Server rules popup shows every time i choose a channel

### ISSUE THREAD

**Issue by kreat0** [uowuo/abaddon#28]
When i choose a channel, a rules popup comes up with the rules and a "Accept" button every single time, even though i am already in the server and accepted those said rules.

**Comment by kreat0** [comment]
the said popup (rules blurred);
![2021-06-24_16-38](https://user-images.githubusercontent.com/10700329/123301032-b485f800-d50a-11eb-839f-87e651be53e1.png)

**Comment by ouwou** [comment]
i think this should fix that, let me know

**Comment by ouwou** [comment]
assuming its working now

**Comment by kreat0** [comment]
It does work fine now.
