### ISSUE TITLE
Error while building (WINDOWS)

### ISSUE THREAD

**Issue by yeyecowboy** [uowuo/abaddon#288]
Hello, I am using MSYS2 to compile Abaddon and I am getting the issue where nlohmann_json isnt found

This is the error:

![image](https://github.com/uowuo/abaddon/assets/96539679/378e43da-b9ec-4f8d-9cbd-39afc0fee346)
  
Could I get any help to resolve this issue?

**Comment by ouwou** [comment]
make sure you are in a MINGW64 shell and not MSYS2

**Comment by yeyecowboy** [comment]
Well now I'm getting this HUGE error, I'm using MINGW64 shell and ran the command ninja inside of the build folder expecting it would actually build it but instead it gave me this, I tried running it as administrator as well, and nothing different happened:


[1/142] Building CXX object CMakeFiles/abaddon.dir/cmake_pch.hxx.gch
FAILED: CMakeFiles/abaddon.dir/cmake_pch.hxx.gch
C:\msys64\usr\bin\c++.exe -DENABLE_NOTIFICATION_SOUNDS -DFMT_SHARED -DIXWEBSOCKET_USE_OPEN_SSL -DIXW
EBSOCKET_USE_TLS -DIXWEBSOCKET_USE_ZLIB -DKEYCHAIN_WINDOWS=1 -DNOMINMAX -DSPDLOG_COMPILED_LIB -DSPDL
OG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -DWITH_KEYCHAIN -DWITH_LIBHANDY -DWITH_MINIAUDIO -DWITH_QRLOGIN
-DWITH_RNNOISE -DWITH_VOICE -D_CRT_SECURE_NO_WARNINGS -IC:/Users/savrl/Downloads/abaddon/IXWEBSOCKET
_INCLUDE_DIRS -IC:/Users/savrl/Downloads/abaddon/src -IC:/Users/savrl/Downloads/abaddon/build -IC:/m
sys64/mingw64/include/gtkmm-3.0 -IC:/msys64/mingw64/lib/gtkmm-3.0/include -IC:/msys64/mingw64/includ
e/gdkmm-3.0 -IC:/msys64/mingw64/lib/gdkmm-3.0/include -IC:/msys64/mingw64/include/gtk-3.0 -IC:/msys6
4/mingw64/include/gdk-pixbuf-2.0 -IC:/msys64/mingw64/include/glibmm-2.4 -IC:/msys64/mingw64/lib/glib
mm-2.4/include -IC:/msys64/mingw64/include/giomm-2.4 -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys6
4/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/lib/giomm-2.4/include -IC:/msys64/mingw64/include
/pangomm-1.4 -IC:/msys64/mingw64/lib/pangomm-1.4/include -IC:/msys64/mingw64/include/pango-1.0 -IC:/
msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/freety
pe2 -IC:/msys64/mingw64/include/cairomm-1.0 -IC:/msys64/mingw64/lib/cairomm-1.0/include -IC:/msys64/
mingw64/include/atkmm-1.6 -IC:/msys64/mingw64/lib/atkmm-1.6/include -IC:/msys64/mingw64/include/atk-
1.0 -IC:/msys64/mingw64/include/sigc++-2.0 -IC:/msys64/mingw64/lib/sigc++-2.0/include -IC:/Users/sav
rl/Downloads/abaddon/subprojects/qrcodegen/cpp -IC:/msys64/mingw64/include/libhandy-1 -IC:/Users/sav
rl/Downloads/abaddon/subprojects/miniaudio -IC:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocke
t -IC:/Users/savrl/Downloads/abaddon/subprojects/keychain/include -IC:/Users/savrl/Downloads/abaddon
/subprojects/rnnoise/include -isystem C:/msys64/mingw64/include -isystem C:/msys64/mingw64/include/o
pus -O2 -g -DNDEBUG -std=gnu++17 -Winvalid-pch -x c++-header -include C:/Users/savrl/Downloads/abadd
on/build/CMakeFiles/abaddon.dir/cmake_pch.hxx -MD -MT CMakeFiles/abaddon.dir/cmake_pch.hxx.gch -MF C
MakeFiles\abaddon.dir\cmake_pch.hxx.gch.d -o CMakeFiles/abaddon.dir/cmake_pch.hxx.gch -c C:/Users/sa
vrl/Downloads/abaddon/build/CMakeFiles/abaddon.dir/cmake_pch.hxx.cxx
<command-line>: fatal error: C:/Users/savrl/Downloads/abaddon/build/CMakeFiles/abaddon.dir/cmake_pch
.hxx: No such file or directory
compilation terminated.
[14/142] Building CXX object subprojects/ixwebso.../ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.obj
FAILED: subprojects/ixwebsocket/CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.obj
C:\msys64\usr\bin\c++.exe -DIXWEBSOCKET_USE_OPEN_SSL -DIXWEBSOCKET_USE_TLS -DIXWEBSOCKET_USE_ZLIB -D
_CRT_SECURE_NO_WARNINGS -IC:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket -isystem C:/msys6
4/mingw64/include -O2 -g -DNDEBUG -std=c++11 -MD -MT subprojects/ixwebsocket/CMakeFiles/ixwebsocket.
dir/ixwebsocket/IXDNSLookup.cpp.obj -MF subprojects\ixwebsocket\CMakeFiles\ixwebsocket.dir\ixwebsock
et\IXDNSLookup.cpp.obj.d -o subprojects/ixwebsocket/CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLook
up.cpp.obj -c C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp: In member func
tion ΓÇÿix::DNSLookup::AddrInfoPtr ix::DNSLookup::getAddrInfo(const std::string&, int, std::string&)
ΓÇÖ:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:52:25: error: a
ggregate ΓÇÿaddrinfo hintsΓÇÖ has incomplete type and cannot be defined
   52 |         struct addrinfo hints;
      |                         ^~~~~
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:54:26: error: Γ
ÇÿAI_ADDRCONFIGΓÇÖ was not declared in this scope
   54 |         hints.ai_flags = AI_ADDRCONFIG | AI_NUMERICSERV;
      |                          ^~~~~~~~~~~~~
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:54:42: error: Γ
ÇÿAI_NUMERICSERVΓÇÖ was not declared in this scope
   54 |         hints.ai_flags = AI_ADDRCONFIG | AI_NUMERICSERV;
      |                                          ^~~~~~~~~~~~~~
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:61:34: error: Γ
ÇÿgetaddrinfoΓÇÖ was not declared in this scope; did you mean ΓÇÿgetAddrInfoΓÇÖ?
   61 |         int getaddrinfo_result = getaddrinfo(hostname.c_str(), sport.c_str(), &hints, &res);
      |                                  ^~~~~~~~~~~
      |                                  getAddrInfo
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:64:22: error: Γ
Çÿgai_strerrorΓÇÖ was not declared in this scope; did you mean ΓÇÿstrerrorΓÇÖ?
   64 |             errMsg = gai_strerror(getaddrinfo_result);
      |                      ^~~~~~~~~~~~
      |                      strerror
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:34: error: Γ
ÇÿfreeaddrinfoΓÇÖ was not declared in this scope; did you mean ΓÇÿgetAddrInfoΓÇÖ?
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                  ^~~~~~~~~~~~
      |                                  getAddrInfo
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: error: n
o matching function for call to ΓÇÿstd::shared_ptr<addrinfo>::shared_ptr(<brace-enclosed initializer
 list>)ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
In file included from /usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/memory:80,
                 from C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLook
up.h:16,
                 from C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLook
up.cpp:20:
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:463:9: note: candidate: ΓÇÿtemplate
<class _Alloc, class ... _Args> std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Ar
gs&& ...) [with _Args = _Alloc; _Tp = addrinfo]ΓÇÖ
  463 |         shared_ptr(_Sp_alloc_shared_tag<_Alloc> __tag, _Args&&... __args)
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:463:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿstd::_Sp_alloc_shared_tag<_Tp>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:404:9: note: candidate: ΓÇÿtemplate
<class _Yp, class _Del, std::shared_ptr<addrinfo>::_Constructible<std::unique_ptr<_Tp, _Dp>, std::__
sp_array_delete>* <anonymous> > std::shared_ptr<_Tp>::shared_ptr(std::unique_ptr<_Up, _Ep>&&) [with
_Del = _Yp; _Constructible<std::unique_ptr<_Up, _Ep>, std::__sp_array_delete>* <anonymous> = _Del; _
Tp = addrinfo]ΓÇÖ
  404 |         shared_ptr(unique_ptr<_Yp, _Del>&& __r)
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:404:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿstd::unique_ptr<_Tp, _Dp>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:395:9: note: candidate: ΓÇÿtemplate
<class _Yp, class _Del, class> std::shared_ptr<_Tp>::shared_ptr(std::unique_ptr<_Up, _Ep>&&) [with _
Del = _Yp; <template-parameter-2-3> = _Del; _Tp = addrinfo]ΓÇÖ
  395 |         shared_ptr(unique_ptr<_Yp, _Del>&& __r)
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:395:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿstd::unique_ptr<_Tp, _Dp>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:387:9: note: candidate: ΓÇÿtemplate
<class _Yp, class> std::shared_ptr<_Tp>::shared_ptr(std::auto_ptr<_Up>&&) [with _Yp = _Tp1; _Tp = ad
drinfo]ΓÇÖ
  387 |         shared_ptr(auto_ptr<_Yp>&& __r);
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:387:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿstd::auto_ptr<_Up>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:380:18: note: candidate: ΓÇÿtemplat
e<class _Yp, class> std::shared_ptr<_Tp>::shared_ptr(const std::weak_ptr<_Yp>&) [with <template-para
meter-2-2> = _Yp; _Tp = addrinfo]ΓÇÖ
  380 |         explicit shared_ptr(const weak_ptr<_Yp>& __r)
      |                  ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:380:18: note:   template argument d
eduction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿconst std::weak_ptr<_Tp>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:368:9: note: candidate: ΓÇÿtemplate
<class _Yp, class> std::shared_ptr<_Tp>::shared_ptr(std::shared_ptr<_Yp>&&) [with <template-paramete
r-2-2> = _Yp; _Tp = addrinfo]ΓÇÖ
  368 |         shared_ptr(shared_ptr<_Yp>&& __r) noexcept
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:368:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿstd::shared_ptr<_Tp>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:351:9: note: candidate: ΓÇÿtemplate
<class _Yp, class> std::shared_ptr<_Tp>::shared_ptr(const std::shared_ptr<_Yp>&) [with <template-par
ameter-2-2> = _Yp; _Tp = addrinfo]ΓÇÖ
  351 |         shared_ptr(const shared_ptr<_Yp>& __r) noexcept
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:351:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿconst std::shared_ptr<_Tp>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:311:9: note: candidate: ΓÇÿtemplate
<class _Yp> std::shared_ptr<_Tp>::shared_ptr(const std::shared_ptr<_Yp>&, element_type*) [with _Tp =
 addrinfo]ΓÇÖ
  311 |         shared_ptr(const shared_ptr<_Yp>& __r, element_type* __p) noexcept
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:311:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
mismatched types ΓÇÿconst std::shared_ptr<_Tp>ΓÇÖ and ΓÇÿaddrinfo*ΓÇÖ
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:287:9: note: candidate: ΓÇÿtemplate
<class _Deleter, class _Alloc> std::shared_ptr<_Tp>::shared_ptr(std::nullptr_t, _Deleter, _Alloc) [w
ith _Alloc = _Deleter; _Tp = addrinfo]ΓÇÖ
  287 |         shared_ptr(nullptr_t __p, _Deleter __d, _Alloc __a)
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:287:9: note:   template argument de
duction/substitution failed:
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:268:9: note: candidate: ΓÇÿtemplate
<class _Yp, class _Deleter, class _Alloc, class> std::shared_ptr<_Tp>::shared_ptr(_Yp*, _Deleter, _A
lloc) [with _Deleter = _Yp; _Alloc = _Deleter; <template-parameter-2-4> = _Alloc; _Tp = addrinfo]ΓÇÖ
  268 |         shared_ptr(_Yp* __p, _Deleter __d, _Alloc __a)
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:268:9: note:   template argument de
duction/substitution failed:
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:248:9: note: candidate: ΓÇÿtemplate
<class _Deleter> std::shared_ptr<_Tp>::shared_ptr(std::nullptr_t, _Deleter) [with _Tp = addrinfo]ΓÇÖ
  248 |         shared_ptr(nullptr_t __p, _Deleter __d)
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:248:9: note:   template argument de
duction/substitution failed:
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:231:9: note: candidate: ΓÇÿtemplate
<class _Yp, class _Deleter, class> std::shared_ptr<_Tp>::shared_ptr(_Yp*, _Deleter) [with _Deleter =
 _Yp; <template-parameter-2-3> = _Deleter; _Tp = addrinfo]ΓÇÖ
  231 |         shared_ptr(_Yp* __p, _Deleter __d)
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:231:9: note:   template argument de
duction/substitution failed:
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:214:9: note: candidate: ΓÇÿtemplate
<class _Yp, class> std::shared_ptr<_Tp>::shared_ptr(_Yp*) [with <template-parameter-2-2> = _Yp; _Tp
= addrinfo]ΓÇÖ
  214 |         shared_ptr(_Yp* __p) : __shared_ptr<_Tp>(__p) { }
      |         ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:214:9: note:   template argument de
duction/substitution failed:
C:/Users/savrl/Downloads/abaddon/subprojects/ixwebsocket/ixwebsocket/IXDNSLookup.cpp:67:47: note:
candidate expects 1 argument, 2 provided
   67 |         return AddrInfoPtr{ res, freeaddrinfo };
      |                                               ^
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:535:7: note: candidate: ΓÇÿstd::sha
red_ptr<_Tp>::shared_ptr(const std::weak_ptr<_Tp>&, std::nothrow_t) [with _Tp = addrinfo]ΓÇÖ
  535 |       shared_ptr(const weak_ptr<_Tp>& __r, std::nothrow_t) noexcept
      |       ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:535:39: note:   no known conversion
 for argument 1 from ΓÇÿaddrinfo*ΓÇÖ to ΓÇÿconst std::weak_ptr<addrinfo>&ΓÇÖ
  535 |       shared_ptr(const weak_ptr<_Tp>& __r, std::nothrow_t) noexcept
      |                  ~~~~~~~~~~~~~~~~~~~~~^~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:412:17: note: candidate: ΓÇÿconstex
pr std::shared_ptr<_Tp>::shared_ptr(std::nullptr_t) [with _Tp = addrinfo; std::nullptr_t = std::null
ptr_t]ΓÇÖ
  412 |       constexpr shared_ptr(nullptr_t) noexcept : shared_ptr() { }
      |                 ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:412:17: note:   candidate expects 1
 argument, 2 provided
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:359:7: note: candidate: ΓÇÿstd::sha
red_ptr<_Tp>::shared_ptr(std::shared_ptr<_Tp>&&) [with _Tp = addrinfo]ΓÇÖ
  359 |       shared_ptr(shared_ptr&& __r) noexcept
      |       ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:359:7: note:   candidate expects 1
argument, 2 provided
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:204:7: note: candidate: ΓÇÿstd::sha
red_ptr<_Tp>::shared_ptr(const std::shared_ptr<_Tp>&) [with _Tp = addrinfo]ΓÇÖ
  204 |       shared_ptr(const shared_ptr&) noexcept = default; ///< Copy constructor
      |       ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:204:7: note:   candidate expects 1
argument, 2 provided
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:202:17: note: candidate: ΓÇÿconstex
pr std::shared_ptr<_Tp>::shared_ptr() [with _Tp = addrinfo]ΓÇÖ
  202 |       constexpr shared_ptr() noexcept : __shared_ptr<_Tp>() { }
      |                 ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-msys/13.2.0/include/c++/bits/shared_ptr.h:202:17: note:   candidate expects 0
 arguments, 2 provided
[18/142] Building CXX object subprojects/ixwebso...ixwebsocket.dir/ixwebsocket/IXHttpClient.cpp.obj
ninja: build stopped: subcommand failed.

**Comment by yeyecowboy** [comment]
I looked inside of abaddon.dir folder and I don't have the cmake_pch.hxx.gch file when I ran this command: "cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo .."

**Comment by yeyecowboy** [comment]
Never mind, I think I fixed it, all I did was remove the package removing mingw-w64-x86_64-gettext using

> pacman -Rdd mingw-w64-x86_64-gettext

and then installed mingw-w64-x86_64-gcc, ran ninja and it worked normally, I have cleared the cache as well before, but I didn't know that i needed mingw-w64-x86_64-gcc, thanks for the help!

**Comment by yeyecowboy** [comment]
Yeah, I saw that after I fixed it when I was looking at the humongous error. I'm trying to make my own version of abaddon so I had to compile it, also would you know by chance if there are any soft clipper or gain limiters inside of abaddons source or anywhere in the other subproject libraries and what not?
