### ISSUE TITLE
[remote-auth-ws] [error] Websocket error: Status: 0 Reason: Unable to connect to remote-auth-gateway.discord.gg on port 443, error: OpenSSL failed - error:0A000086:SSL routines::certificate verify failed

### ISSUE THREAD

**Issue by AlexAnimateMp4** [uowuo/abaddon#289]
Hello !
I get this error when I set a token or click on the QR code login option.

<img width="601" alt="Client" src="https://github.com/uowuo/abaddon/assets/48261899/4be6fd17-5969-434f-81f3-2446b0eddb50">
<img width="674" alt="Console" src="https://github.com/uowuo/abaddon/assets/48261899/4dfe2002-a2d4-4904-9c99-8705603fd1c2">
<img width="345" alt="Windows" src="https://github.com/uowuo/abaddon/assets/48261899/88967d60-bde8-48f0-9437-bab4750da612">

**Comment by ouwou** [comment]
do you get a popup that says failed to fetch build number or cookies as well? and can you connect if you manually set your token?

**Comment by ouwou** [comment]
reopen if you still have an issue here
