### ISSUE TITLE
macOS needs a several fixes for subprojects: how to do that, technically?

### ISSUE THREAD

**Issue by barracuda156** [uowuo/abaddon#294]
@ouwou Is there some mechanism to patch subprojects after fetching? Several fix-ups are needed. I have submitted PRs to respective upstreams, but no one knows how long it gonna take to merge, since some of those may not be actively maintained.

**Comment by ouwou** [comment]
i missed this but is this still something to keep open? im not sure how you would patch outside of just using git for it. would that not suffice ?

**Comment by barracuda156** [comment]
@ouwou I actually patched out fetching modules completely and use independently installed dependencies (as separate ports). This is generally preferably and also solved an issue with patching wherever needed.
So can be closed.
