### ISSUE TITLE
abaddon.exe - System Error

### ISSUE THREAD

**Issue by ucjd** [uowuo/abaddon#307]
on the latest github version of abaddon (the CI one) there is a bug everytime i run the abaddon.exe on windows it says this:
The code execution cannot proceed because libnghttp3-9.dll was not found. Reinstalling the program may fix this problem.
and yes i have reinstalled and all that, but when i download the newest release version it works just fine and its been ever since it got updated.

**Comment by ouwou** [comment]
should be good now
