### ISSUE TITLE
build number could not be fetched

### ISSUE THREAD

**Issue by LittleYoungBlud** [uowuo/abaddon#310]
it keeps saying build number could not be fetched and also keeps rejecting my token

**Comment by ouwou** [comment]
see if build number is still an issue in the latest build: https://nightly.link/uowuo/abaddon/workflows/ci/master/build-windows-msys2-MinSizeRel.zip

if discord is rejecting your token then you are pasting it in incorrectly

**Comment by ouwou** [comment]
forgot to update so that link will work in about 15mins

**Comment by Sohail-XD** [comment]
This issue seems to be solved. You could close this one.

**Comment by LittleYoungBlud** [comment]
> see if build number is still an issue in the latest build: https://nightly.link/uowuo/abaddon/workflows/ci/master/build-windows-msys2-MinSizeRel.zip
> 
> if discord is rejecting your token then you are pasting it in incorrectly

its still an issue i clicked the link u sent it still pops up the same error

**Comment by LittleYoungBlud** [comment]
> see if build number is still an issue in the latest build: https://nightly.link/uowuo/abaddon/workflows/ci/master/build-windows-msys2-MinSizeRel.zip
> 
> if discord is rejecting your token then you are pasting it in incorrectly

wait it works now nvm thanks yo

**Comment by makufelis** [comment]
same issue again

**Comment by Sohail-XD** [comment]
yep, it's back

**Comment by ucjd** [comment]
it worked for a bit but now its happening again

**Comment by ouwou** [comment]
fixed

**Comment by makufelis** [comment]
download link?

**Comment by ouwou** [comment]
its in the readme https://nightly.link/uowuo/abaddon/workflows/ci/master/build-windows-msys2-MinSizeRel.zip
