### ISSUE TITLE
build number could not be fetched

### ISSUE THREAD

**Issue by Sohail-XD** [uowuo/abaddon#319]
This error is back again, i updated the aur package with devel, it was fine till yesterday. Is there no permanent solution for this?

**Comment by ouwou** [comment]
the build number is part of the info discord sends to the server when connecting so i like to keep it updated in the hopes it decreases the risk of getting picked up by anti-spam. theres no easy way to get it so its semi-hardcoded to pull it from a particular script. i could have it scan every script but having to download and process 20mb of data every time you launch it isnt an acceptable solution. if it keeps breaking (usually its good for a couple months) ill consider something like having abaddon pull the number from a github repo which updates it 24/7 thru actions
