### ISSUE TITLE
HELLO ALL - SERIOUS INQUIRY

### ISSUE THREAD

**Issue by ayush-kumar-dev** [uowuo/abaddon#32]
Hi, I would like to start this issue by talking a little bit about me, my name is Ayush Kumar, and im a junior dev from 🇮🇳 😘. I enjoy software very much, and hate electron !! this project is a godsend but as it is very new I would like to know if it is safe from vyrus 😭, can anyone audit !! ? thank

**Comment by ouwou** [comment]
Yes Sir i have Third Party auditings that Confirmationings of the safeties .. Thank you from Abu Dubai Delhi

**Comment by ayush-kumar-dev** [comment]
this is not very reassure, u are first party 😤

**Comment by ayush-kumar-dev** [comment]
REOPEN ISSUE NOW THIS IS NOT WHAT OPEN SOURSE IS FOR
