### ISSUE TITLE
both AUR packages failing right now

### ISSUE THREAD

**Issue by Seme4eg** [uowuo/abaddon#330]
`yay -S abaddon` yields:

```
/home/earthian/.cache/yay/abaddon/src/abaddon/src/abaddon.cpp:85:0:   required from here
   85 |         spdlog::get("voice")->debug("{} SSRC: {}", m.UserID, m.SSRC);
/usr/include/fmt/base.h:1402:29: error: passing ‘const fmt::v11::formatter<Snowflake>’ as ‘this’ argument discards qualifiers [-fpermissive]
 1402 |     ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));
      |                    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/earthian/.cache/yay/abaddon/src/abaddon/src/discord/snowflake.hpp:47:10: note:   in call to ‘fmt::v11::context::iterator fmt::v11::formatter<Snowflake>::format(Snowflake, fmt::v11::format_context&)’
   47 |     auto format(Snowflake id, format_context &ctx) -> decltype(ctx.out()) {
      |          ^~~~~~
[ 49%] Building CXX object CMakeFiles/abaddon.dir/src/components/lazyimage.cpp.o
[ 50%] Building CXX object CMakeFiles/abaddon.dir/src/components/memberlist.cpp.o
[ 51%] Building CXX object CMakeFiles/abaddon.dir/src/components/progressbar.cpp.o
[ 52%] Building CXX object CMakeFiles/abaddon.dir/src/components/ratelimitindicator.cpp.o
[ 52%] Building CXX object CMakeFiles/abaddon.dir/src/components/voiceinfobox.cpp.o
make[2]: *** [CMakeFiles/abaddon.dir/build.make:109: CMakeFiles/abaddon.dir/src/abaddon.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/abaddon.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/earthian/.cache/yay/abaddon/src/build'
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: abaddon-exit status 4
 ```
 
 `yay -S abaddon-git` yields:

```
AUR Explicit (1): abaddon-git-0.1.11.r103.g9724023-1
:: PKGBUILD up to date, skipping download: abaddon-git
 -> error resetting /home/earthian/.cache/yay/abaddon-git: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Arch linux btw, Hpyrland

**Comment by smolBlackCat** [comment]
Interesting. Do you mind informing your C++ compiler version? This is easily solvable by using adding `const` to the std::formatter method in Snowflake. I'm only asking this because I came across the same issue while writing the i18n patch

**Comment by Seme4eg** [comment]
@smolBlackCat - `cmake version 3.30.4`. Same issue persists even after i updated the compiler to new version `3.30.5-1`

**Comment by smolBlackCat** [comment]
I meant the C++ compiler, not the build system

**Comment by Seme4eg** [comment]
well i am not a c++ dev, i am looking at aur pkgbuild and its running cmake and make, that's why i sent versions of those. Tell me which commands to run in the terminal and i will share the output no problem, sir.

**Comment by Seme4eg** [comment]
gcc (GCC) 14.2.1 20240910

**Comment by smolBlackCat** [comment]
Oh, it seems the problem has already been solved by a recent commit (28527efb83161905e924cfc9d08391c0db737ec3). I believe the AUR is just not up-to-date yet

**Comment by Seme4eg** [comment]
well, as i reported, yay -S abaddon-git is also failing) logs above. It should be building from latest commit, but it's failing right after ocmmand is ran.

**Comment by smolBlackCat** [comment]
![image](https://github.com/user-attachments/assets/a7e82342-c750-4ed5-b893-f08219f7088f)
The AUR is indeed not up-to-date. The AUR was last updated around a month ago. I believe it's better to forward this issue to the AUR maintainer.

**Comment by Seme4eg** [comment]
I diffed the pkgbuilds of abaddon and abaddon-git and there are no major differences, so i just cleared the abaddon-git yay cache and cleanbuilt the package. And that fixed the issue. Thank you for quick responses, sir!
