### ISSUE TITLE
Missing DLL Error: libfmt-11.dll

### ISSUE THREAD

**Issue by ucjd** [uowuo/abaddon#332]
I encountered an error while trying to run the program abaddon.exe. The error message reads:
The code execution cannot proceed because libfmt-11.dll was not found. Reinstalling the program may fix this problem.

**Comment by ucjd** [comment]
You didn’t fix it; you can see the version at the top (9b8c8c4), and the error is still there.
![image](https://github.com/user-attachments/assets/b61dfaa6-150a-449e-b4d6-b0ea8a50bc51)

**Comment by ouwou** [comment]
thats confusing

**Comment by ouwou** [comment]
oh im stupid

**Comment by ucjd** [comment]
works now
