### ISSUE TITLE
Crash when opening direct messages

### ISSUE THREAD

**Issue by Zander671** [uowuo/abaddon#37]
It seems I am experiencing the same issue described #26. Whenever I open anything under direct messages, abaddon crashes. I am using Arch Linux with everything fully updated. I installed abaddon using the 'abaddon-git' AUR package.
Here is the output:
> sending {"d":null,"op":1}
> sending {"d":{"capabilities":125,"client_state":{"guild_hashes":{},"highest_last_message_id":"0","read_state_version":0,"user_guild_settings_version":-1},"compress":false,"presence":{"activities":[],"afk":false,"since":0,"status":"online"},"properties":{"browser":"Chrome","browser_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36","browser_version":"67.0.3396.87","client_build_number":91734,"client_event_source":null,"device":"","os":"Windows","os_version":"10","referrer":"","referrer_current":"","referring_domain":"","referring_domain_current":"","release_channel":"stable","system_locale":"en-US"},"token":"\<SECRET\>"},"op":2}
> /usr/include/c++/11.1.0/optional:447: constexpr const _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() const [with _Tp = Snowflake; _Dp = std::_Optional_base<Snowflake, true, true>]: Assertion 'this->_M_is_engaged()' failed.
/usr/bin/abaddon: line 3: 2057528 Aborted                 (core dumped) ./abaddon

To get this output, I just launched abaddon from the command line and clicked on a DM.

**Comment by javsanpar** [comment]
abaddon AUR maintainer here! I will try to reproduce your problem and see if there is any bug in the packages.

**Comment by Zander671** [comment]
I don't think it has much information, but here is the output from gdb. I don't know how to get the AUR package to generate debug symbols.

> #0  0x00007ffff64b2d22 in raise () at /usr/lib/libc.so.6
> #1  0x00007ffff649c862 in abort () at /usr/lib/libc.so.6
> #2  0x000055555564548a in  ()
> #3  0x00005555556a19ff in  ()
> #4  0x0000555555802b61 in  ()
> #5  0x000055555563ff67 in  ()
> #6  0x0000555555664d45 in  ()
> #7  0x00005555556551c2 in  ()
> #8  0x00007ffff7cf817d in  () at /usr/lib/libgtkmm-3.0.so.1
> #9  0x00007ffff6427d8f in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
> #10 0x00007ffff6443718 in  () at /usr/lib/libgobject-2.0.so.0
> #11 0x00007ffff6444dd9 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
> #12 0x00007ffff6445330 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
> #13 0x00007ffff751161c in  () at /usr/lib/libgtk-3.so.0
> #14 0x00007ffff729628b in  () at /usr/lib/libgtk-3.so.0
> #15 0x00007ffff64451c0 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
> #16 0x00007ffff6445330 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
> #17 0x00007ffff739ff2d in  () at /usr/lib/libgtk-3.so.0
> #18 0x00007ffff642c4ac in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib/libgobject-2.0.so.0
> #19 0x00007ffff64451c0 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
> #20 0x00007ffff6445330 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
> #21 0x00007ffff7397598 in  () at /usr/lib/libgtk-3.so.0
> #22 0x00007ffff739f73b in  () at /usr/lib/libgtk-3.so.0
> #23 0x00007ffff73a0374 in  () at /usr/lib/libgtk-3.so.0
> #24 0x00007ffff7366213 in gtk_event_controller_handle_event () at /usr/lib/libgtk-3.so.0
> #25 0x00007ffff7539a0f in  () at /usr/lib/libgtk-3.so.0
> #26 0x00007ffff72949e5 in  () at /usr/lib/libgtk-3.so.0
> #27 0x00007ffff64451c0 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
> #28 0x00007ffff6445330 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
> #29 0x00007ffff7548af5 in  () at /usr/lib/libgtk-3.so.0
> #30 0x00007ffff73e99b5 in  () at /usr/lib/libgtk-3.so.0
> #31 0x00007ffff73ea8d3 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
> #32 0x00007ffff635d643 in  () at /usr/lib/libgdk-3.so.0
> #33 0x00007ffff63a89f4 in  () at /usr/lib/libgdk-3.so.0
> #34 0x00007ffff6edc4dc in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
> #35 0x00007ffff6f30749 in  () at /usr/lib/libglib-2.0.so.0
> #36 0x00007ffff6ed9bc1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
> #37 0x00007ffff61b72ee in g_application_run () at /usr/lib/libgio-2.0.so.0
> #38 0x00007ffff649db25 in __libc_start_main () at /usr/lib/libc.so.6
> #39 0x000055555563756e in  ()

**Comment by ouwou** [comment]
ok i think i fixed this one with the latest commit. lemme know if it works.

**Comment by Zander671** [comment]
It seems to work perfectly! Thank you. ^_^

**Comment by iraizo** [comment]
This is still happening for me, installed from aur
