### ISSUE TITLE
Show unread server and channels

### ISSUE THREAD

**Issue by DUOLabs333** [uowuo/abaddon#43]
In the official Discord client, there's a white dot on the server list for any server with messages you haven't read yet, and the specific channels are boldened in white. So, is it possible to do that here?

**Comment by ouwou** [comment]
yeah this is something ive wanted to do for a while and will probably start working on soon

**Comment by ouwou** [comment]
in 0.1.3 now

**Comment by DUOLabs333** [comment]
Doesn't work for me if you build it from git.

**Comment by ouwou** [comment]
are you using the aur package? perhaps its tied to a single commit. otherwise i see no reason why it wouldnt work, assuming by "doesn't work" you mean no indicators show up.

**Comment by DUOLabs333** [comment]
No, I just pulled straight from the git repository.

**Comment by DUOLabs333** [comment]
Never mind, I see it now -- I just didn't realize it was a white rectangle, instead of a dot.

**Comment by DUOLabs333** [comment]
Maybe also bolden the text?

**Comment by ouwou** [comment]
maybe. i think i tried that once and it didnt look very good. i might mess around with it again and if i come up with something that looks nice ill make it an option
