### ISSUE TITLE
Compilation issue on Arch linux

### ISSUE THREAD

**Issue by AdverseMiller** [uowuo/abaddon#50]
I'm trying to compile on arch and I just keep getting this issue:

_usr/bin/ld:_ /usr/local/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): undefined reference to symbol 'SSL_load_client_CA_file@@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib/libssl.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/abaddon.dir/build.make:1206: abaddon] Error 1
make[2]: Leaving directory '/home/andrew/programs/abaddon-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/abaddon.dir/all] Error 2
make[1]: Leaving directory '/home/andrew/programs/abaddon-git/src/build'
make: *** [Makefile:91: all] Error 2
make: Leaving directory '/home/andrew/programs/abaddon-git/src/build'_

I tried cloning directly from the repository, and also tried the arch AUR package for abaddon

**Comment by ouwou** [comment]
i think it might be because of the capitalization. can you try renaming cmake/Findixwebsocket.cmake to cmake/FindIXWebSocket.cmake ?

**Comment by AdverseMiller** [comment]
where would Findixwebsocket.cmake be located?

**Comment by ouwou** [comment]
when you cloned the repo, it would be [abaddon/cmake/Findixwebsocket.cmake](https://github.com/uowuo/abaddon/blob/master/cmake/Findixwebsocket.cmake)

**Comment by AdverseMiller** [comment]
It worked! But I also get errors "The emoji file couldn't be loaded!" and "The Discord cache could not be created!"

**Comment by MedzikUser** [comment]
[](https://cdn.magicuser.cf/olMtZBk.png)

**Comment by ouwou** [comment]
> It worked! But I also get errors "The emoji file couldn't be loaded!" and "The Discord cache could not be created!"

well the emoji file thing is because the `res/res` folder wasnt found. i bet if you use the AUR package it should take care of that (ill commit fix in a minute).

the cache thing is strange. i think it would make sense to open a separate issue for that

**Comment by AdverseMiller** [comment]
You were right, the AUR package does fix the emoji issue, now regarding the cache issue, I don't know if this helps, but running the abaddon binary in /usr/bin returns this:
_failed to clear database: database disk image is malformed
	database disk image is malformed_

**Comment by ouwou** [comment]
could you do another issue for that?

**Comment by AdverseMiller** [comment]
yep
