### ISSUE TITLE
The Discord cache could not be created!

### ISSUE THREAD

**Issue by AdverseMiller** [uowuo/abaddon#51]
I'm running Arch Linux with abaddon installed from the AUR and from git. When running the abaddon binary, I get the error "The Discord cache could not be created!'

**Comment by ouwou** [comment]
the database tries to create itself at the path [std::filesystem::temp_directory_path()](https://en.cppreference.com/w/cpp/filesystem/temp_directory_path) returns. i guess on arch this would be `/tmp`? perhaps theres something preventing it from writing files there? maybe try setting the TMPDIR environment var to somewhere else and see what happens, and also check if it actually manages to create anything in `/tmp` (it should create 3 files)

**Comment by AdverseMiller** [comment]
I wrote a quick c++ program to output what "std::filesystem::temp_directory_path() " and it does equal /tmp. I checked /tmp and it created nothing in the directory. I used ln -s to link /tmp to a different directory and still nothing :(

**Comment by ouwou** [comment]
well make sure you leave it open when checking because the file is deleted when closed. `/tmp` seems to use some weird filesystem stuff im not familiar with so idk if a link would have worked. did you try changing one of TMPDIR, TMP, TEMP, TEMPDIR? or perhaps you can try specifying a path [here](https://github.com/uowuo/abaddon/blob/master/src/discord/store.cpp#L9) to try and see if any paths work. is the extended error message still something about a malformed disk image?

**Comment by AdverseMiller** [comment]
I changed my $TEMPDIR to ~/cache and "std::filesystem::temp_directory_path()" outputs the new path. I tried changing the directory in src/discord/store.cpp still with no luck. The error message still includes malformed disk image.

**Comment by ouwou** [comment]
thats weird... does using an in-memory database work? add `memory_db=true` to the `[discord]` section in abaddon.ini

**Comment by AdverseMiller** [comment]
abaddon.ini exists, but the file is empty

**Comment by ouwou** [comment]
lol makes sense since you never actually were able to set a token. just add this to the file
```
[discord]
memory_db=true
```

**Comment by AdverseMiller** [comment]
issue still persists :(

**Comment by ouwou** [comment]
and you undid your changes in store.cpp to make sure it took effect? also this kind of back and forth might be better for the discord server if you wanna join
