### ISSUE TITLE
Discord cache could not be created/database disk image is malformed

### ISSUE THREAD

**Issue by LesbianMenace** [uowuo/abaddon#53]
Hi! I'm having an issue trying to launch the application. Since I'm running Arch, I installed the it through the AUR, but whenever I try to open the app I get an error, "The Discord cache could not be created!" When I launch it from a terminal it also gives me "failed to clear database: database disk image is malformed"
So glad to see this project though!!

**Comment by ouwou** [comment]
i believe this is fixed in master, can you try the git package?

**Comment by javsanpar** [comment]
Maybe I should cherry pick the fix and apply it to the package

**Comment by ouwou** [comment]
> Maybe I should cherry pick the fix and apply it to the package until the new version is released

maybe, i plan on tagging a release pretty soon anyways (hopefully within a week or so) after i finish up the last bits of unread indicators

**Comment by ouwou** [comment]
i assume this is the same bug that was already fixed in master. if it still happens somehow on 0.1.3/master feel free to reopen

**Comment by Shatur** [comment]
Can reproduce it on 0.1.3

**Comment by ouwou** [comment]
> Can reproduce it on 0.1.3 (clean installation).

ok i think i know why. ill try and have a fix in a bit
