### ISSUE TITLE
Personal Issue when running make on macOS

### ISSUE THREAD

**Issue by toylatte** [uowuo/abaddon#59]
I'm getting an error saying
`/usr/local/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: 'hb.h' file not found`
But I already have harfbuzz installed. What's wrong?

**Comment by ouwou** [comment]
what do the HARFBUZZ_* variables contain in CMakeCache.txt?

**Comment by toylatte** [comment]
Okay I checked the file and changed the harfbuzz version to the right number (4.0.0 to 4.0.1). But now it says,
`/usr/local/Cellar/cairo/1.16.0_5/include/cairo/cairo-ft.h:50:10: fatal error: 'fontconfig/fontconfig.h' file not found`
But this time CMakeCache seems to have the right version for my brew installation of fontconfig for the keys containing Cairo flags.

**Comment by ouwou** [comment]
im not super familiar with how CMake would work on mac (i only have "experience" with it in getting the CI to pass), but i think it would be using pkg-config. what does it return if you run say `pkg-config pango --libs --cflags`? i might have messed up handling that somewhere down the line

**Comment by toylatte** [comment]
`pkg-config cairo --libs --cflags` gives me


`-I/usr/local/Cellar/libffi/3.4.2/include -I/usr/local/Cellar/cairo/1.16.0_5/include/cairo -I/usr/local/Cellar/glib/2.70.4/include -I/usr/local/Cellar/glib/2.70.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.70.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.45/include -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/libxcb/1.14_2/include -I/usr/local/Cellar/libxrender/0.9.10/include -I/usr/local/Cellar/libxext/1.3.4/include -I/usr/local/Cellar/libx11/1.7.3.1/include -I/usr/local/Cellar/libxcb/1.14_2/include -I/usr/local/Cellar/libxau/1.0.9/include -I/usr/local/Cellar/libxdmcp/1.1.3/include -I/usr/local/Cellar/xorgproto/2021.5/include -L/usr/local/Cellar/cairo/1.16.0_5/lib -lcairo`

**Comment by ouwou** [comment]
can you try applying this? its not really a fix but if this works then i can add a workaround until i get around to redoing the find modules

```diff
diff --git a/cmake/Findpango.cmake b/cmake/Findpango.cmake
index 9313471..5d3971a 100644
--- a/cmake/Findpango.cmake
+++ b/cmake/Findpango.cmake
@@ -64,8 +64,8 @@ find_library(PANGOFT2_LIBRARY
              PATH_SUFFIXES ${PANGO_LIBRARY_NAME}
                            ${PANGO_LIBRARY_NAME}/include)
 
-set(PANGO_LIBRARIES    ${PANGO_LIBRARY};${HARFBUZZ_LIBRARIES};${CAIRO_LIBRARIES};${FREETYPE_LIBRARIES};${PANGOCAIRO_LIBRARY};${PANGOFT2_LIBRARY})
-set(PANGO_INCLUDE_DIRS ${PANGO_INCLUDE_DIR};${PANGO_CONFIG_INCLUDE_DIRS};${HARFBUZZ_INCLUDE_DIR};${CAIRO_INCLUDE_DIRS};${FREETYPE_INCLUDE_DIRS})
+set(PANGO_LIBRARIES    ${PC_PANGO_LIBRARIES};${PANGO_LIBRARY};${HARFBUZZ_LIBRARIES};${CAIRO_LIBRARIES};${FREETYPE_LIBRARIES};${PANGOCAIRO_LIBRARY};${PANGOFT2_LIBRARY})
+set(PANGO_INCLUDE_DIRS ${PC_PANGO_INCLUDE_DIRS};${PANGO_INCLUDE_DIR};${PANGO_CONFIG_INCLUDE_DIRS};${HARFBUZZ_INCLUDE_DIR};${CAIRO_INCLUDE_DIRS};${FREETYPE_INCLUDE_DIRS})
 
 include(FindPackageHandleStandardArgs)
 find_package_handle_standard_args(pango
```

**Comment by toylatte** [comment]
It still says
```
/usr/local/Cellar/cairo/1.16.0_5/include/cairo/cairo-ft.h:50:10: fatal error: 'fontconfig/fontconfig.h' file not found
#include <fontconfig/fontconfig.h>
```
Isn't this an issue with cairo and not pango?

**Comment by ouwou** [comment]
> Isn't this an issue with cairo and not pango?

yeah i confused myself since the first comment was a issue with pango, but actually i would like to know if that patch fixes the harfbuzz error anyways without the changes you made

this should try and include fontconfig if its present period and hopefully that takes care of that

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index fa56d6c..181ab62 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -29,9 +29,6 @@ endif()
 if(WIN32)
 	add_compile_definitions(_CRT_SECURE_NO_WARNINGS)
 	add_compile_definitions(NOMINMAX)
-
-	find_package(Fontconfig REQUIRED)
-	link_libraries(${Fontconfig_LIBRARIES})
 endif()
 
 configure_file(${PROJECT_SOURCE_DIR}/src/config.h.in ${PROJECT_BINARY_DIR}/config.h)
@@ -79,6 +76,11 @@ if (Threads_FOUND)
 	target_link_libraries(abaddon Threads::Threads)
 endif()
 
+find_package(Fontconfig)
+if(Fontconfig_FOUND)
+	target_link_libraries(abaddon Fontconfig::Fontconfig)
+endif()
+
 target_link_libraries(abaddon ${SQLite3_LIBRARIES})
 target_link_libraries(abaddon ${GTKMM_LIBRARIES})
 target_link_libraries(abaddon ${CURL_LIBRARIES})
```

**Comment by ouwou** [comment]
if you wanna come back to this feel free to reopen but since i havent heard back in a bit ill close it for now. ill probably indirectly fix this at some point when/if i redo the find modules
