### ISSUE TITLE
"Connect" grayed out on Manjaro Linux

### ISSUE THREAD

**Issue by pipipear** [uowuo/abaddon#61]
I pasted my token in the set token dialogue and the Connect option in the menu stayed grayed out. After restarting Abaddon, the token shows up in `~/.config/abaddon/abaddon.ini`, but the Connect option is still grayed out.

**Comment by pipipear** [comment]
It turns out the Connect option is only clickable if the Application Menu is removed from the title bar in KDE Plasma.
![04 13 2022-23 22 28](https://user-images.githubusercontent.com/65990558/163326211-02270e31-31ef-4a44-890a-7e51cf92bf47.png)![04 13 2022-23 23 31](https://user-images.githubusercontent.com/65990558/163326228-644fc7ff-403c-41f4-8b13-3bf137956d1c.png)

**Comment by ouwou** [comment]
oh i think i see the issue. the callback that runs for updating the menu doesnt get called in the first case since its outside of the GTK window, so this would have broken last week by 61cde0f7e173379b97823919899171c0ccac2353 when i tried to fix other menu stuff. ill have to think of a workaround since updating the menu as its opened seems to be kind of difficult to do properly in GTK

**Comment by ouwou** [comment]
can you try applying this? i doubt it will work but it would be rather convenient if it did. if not, ill probably have a fix by tomorrow

```diff
diff --git a/src/windows/mainwindow.cpp b/src/windows/mainwindow.cpp
index e12e9bd..d3f922d 100644
--- a/src/windows/mainwindow.cpp
+++ b/src/windows/mainwindow.cpp
@@ -237,11 +237,8 @@ void MainWindow::SetupMenu() {
     m_menu_bar.append(m_menu_view);
     m_menu_bar.show_all();
 
-    m_menu_bar.signal_event().connect([this](GdkEvent *ev) -> bool {
-        OnViewSubmenuPopup();
-        OnDiscordSubmenuPopup();
-        return false;
-    });
+    m_menu_view.signal_event().connect([this](GdkEvent *ev) -> bool { OnViewSubmenuPopup(); return false; }, false);
+    m_menu_discord.signal_event().connect([this](GdkEvent *ev) -> bool { OnDiscordSubmenuPopup(); return false; }, false);
 
     m_menu_discord_connect.signal_activate().connect([this] {
         m_signal_action_connect.emit();
```

**Comment by ouwou** [comment]
im pretty confident the latest commit fixes this. feel free to reopen if theres any other issues
