### ISSUE TITLE
[Question] Can I stay private using this application ? 

### ISSUE THREAD

**Issue by prorounak2005** [uowuo/abaddon#71]
I was finding a frontend to discord because I would never install proprietary grabage like discord on linux. So my question is if I use this application can I stay safe from all tracker and ads which discord serves us ? Because my friends are on discord and I have to use it.

**Comment by ouwou** [comment]
the only requests that are made are those that are necessary. the primary tracking endpoint in discord is `/science` and there are no calls made to that in abaddon because its not necessary. basically its about as private as you can get with discord
