### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Rommmmaha** [uowuo/abaddon#72]
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find gtkmm (missing: GTKMM_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findgtkmm.cmake:53 (find_package_handle_standard_args)
  CMakeLists.txt:14 (find_package)
```
I already have **gtkmm**
![image](https://user-images.githubusercontent.com/53641123/168444422-35cefeac-4c4d-4ce5-a006-05c347b564ae.png)
_I do not know how to use Linux at all, please explain clearly for a beginner_

**Comment by ouwou** [comment]
it's gtkmm 3, so you only want the first package there. i dont know what distribution you use or anything else about your environment so theres not really much i can say. and im not much of a linux expert either. but it seems like a pretty straightforward error, it cant find gtkmms header files.
does pkg-config succeed? `pkg-config gtkmm-3.0 --cflags --libs`

**Comment by Rommmmaha** [comment]
Thanks, it helped, everything works fine. (Linux Manjaro)
