### ISSUE TITLE
Not working on Windows x64, v.0.1.6. The PNG and GIF "pixbuffloader" files weren't detected

### ISSUE THREAD

**Issue by BloodDragooner** [uowuo/abaddon#75]
I wanted to update Abaddon after a while of not using it, turns out it's not working :( I just extracted the latest version from the releases tab and it threw out that error. Any way to debug? Thanks!

**Comment by ouwou** [comment]
make sure you extracted it as-is and launch it from the right location, gtk is a little picky about that. it should look like this

```
/bin
  /css
  /fonts
  /res
  abaddon.exe
  bunch of .dlls
/lib
  /gdk-pixbuf-2.0
    /2.10.0
      ...
/share
  ...
/ssl
  ...
```

and make sure you launch while in the `bin` directory. you would get that error if it cant find the `lib` directory

**Comment by BloodDragooner** [comment]
Sorry for the really late reply, but I did not figure this out, so I grabbed a build from the github actions, and now it works fine. Thank you!!

**Comment by ouwou** [comment]
> Sorry for the really late reply, but I did not figure this out, so I grabbed a build from the github actions, and now it works fine. Thank you!!

strange since the release is basically a copy of the actions build but ¯\\\_(ツ)_/¯

**Comment by Mod4rchive** [comment]
I had the same problem. It seems the build in releases only contains the bin folder for some reason (Windows). I also just downloaded the build from Actions.
