### ISSUE TITLE
Can't join servers

### ISSUE THREAD

**Issue by prorounak2005** [uowuo/abaddon#83]
I clicked on Discord > Accept Invite 
and then I tried to join a discord server. 
For ex this one -https://discord.com/invite/gogo 
and click on the ok button but I cannot join the server. :'(

Anyway to fix it ? 
I am using arch ( https://aur.archlinux.org/packages/abaddon ).

**Comment by ouwou** [comment]
when you enter the link, does it show the preview? (server title + member count) and when you click ok does it show in the console `POST /invites/gogo`? the example you gave me works fine on my end

**Comment by prorounak2005** [comment]
> when you enter the link, does it show the preview? (server title + member count) and when you click ok does it show in the console `POST /invites/gogo`? the example you gave me works fine on my end

Yes!! It shows the server name and 25069 members but when I click on ok nothing happens.

**Comment by ouwou** [comment]
thats strange the only reason nothing would even print to console should be if the dialog doesnt return the OK response

can you try applying this patch and see what it displays in console when you click ok?

```diff
diff --git a/src/abaddon.cpp b/src/abaddon.cpp
index 2e8ecaa..03624c0 100644
--- a/src/abaddon.cpp
+++ b/src/abaddon.cpp
@@ -648,9 +648,10 @@ void Abaddon::ActionSetToken() {
 void Abaddon::ActionJoinGuildDialog() {
     JoinGuildDialog dlg(*m_main_window);
     auto response = dlg.run();
+    printf("%d %s\n", response, dlg.GetCode().c_str());
     if (response == Gtk::RESPONSE_OK) {
         auto code = dlg.GetCode();
-        m_discord.JoinGuild(code);
+        // m_discord.JoinGuild(code);
     }
 }
```

the part that actually joins the server is commented out since joining servers repeatedly (ie while testing) can temporarily restrict your account

**Comment by prorounak2005** [comment]
> thats strange the only reason nothing would even print to console should be if the dialog doesnt return the OK response
> 
> can you try applying this patch and see what it displays in console when you click ok?
> 
> ```diff
> diff --git a/src/abaddon.cpp b/src/abaddon.cpp
> index 2e8ecaa..03624c0 100644
> --- a/src/abaddon.cpp
> +++ b/src/abaddon.cpp
> @@ -648,9 +648,10 @@ void Abaddon::ActionSetToken() {
>  void Abaddon::ActionJoinGuildDialog() {
>      JoinGuildDialog dlg(*m_main_window);
>      auto response = dlg.run();
> +    printf("%d %s\n", response, dlg.GetCode().c_str());
>      if (response == Gtk::RESPONSE_OK) {
>          auto code = dlg.GetCode();
> -        m_discord.JoinGuild(code);
> +        // m_discord.JoinGuild(code);
>      }
>  }
> ```
> 
> the part that actually joins the server is commented out since joining servers repeatedly (ie while testing) can temporarily restrict your account

Can u tell me how to add this patch ?

**Comment by ouwou** [comment]
if you have the repo cloned you can save it to a file and do `git apply file.diff` or just manually insert it yourself since its only 2 lines

**Comment by ouwou** [comment]
i just remembered that captchas can be shown sometimes when trying to join a server, which might be the issue here. i might try and handle that (show a dialog) or just remove the ability to join servers altogether since its prone to spam detection

**Comment by ouwou** [comment]
ive opted to remove it. maybe ill revisit it some other time but the captchas and spam filter are annoying to deal with right now
