### ISSUE TITLE
SIGABRT after attempting to view someone's profile

### ISSUE THREAD

**Issue by epixinvites** [uowuo/abaddon#85]
extracted from coredumpctl -> https://termbin.com/7r6j

**Comment by ouwou** [comment]
does it only occur after viewing profiles? or on other requests too

**Comment by ouwou** [comment]
can you try applying this patch? this whole part of the code is due for a rewrite but maybe this can work as a temporary fix
[85.txt](https://github.com/uowuo/abaddon/files/9129845/85.txt)

**Comment by epixinvites** [comment]
Alright

**Comment by ouwou** [comment]
did it work :^)

**Comment by epixinvites** [comment]
Sorry, tad bit busy these days, will apply it when I have the time.

**Comment by notcancername** [comment]
can't reproduce, link's dead.

**Comment by ouwou** [comment]
reopen if still issue
