### ISSUE TITLE
Just got banned. Feeling good!

### ISSUE THREAD

**Issue by Maximal98** [uowuo/abaddon#87]
Right so as i was testing my crappy patch to hide inaccessible channels, i tried to leave the server that i owned, which resulted in discord sussing me out and temp deactivating my account, then i went in the webclient and left another, different test server and then got banned from discord.
![image](https://user-images.githubusercontent.com/55159959/182045070-79dabf4c-b497-40c9-9e2f-0dbfd473354d.png)
moral of the story: dont leave your own server. you'll die and get put into JAIL for being CRINGE!

**Comment by ouwou** [comment]
yeah this is kind of inevitable when using 3rd party clients. if you [appeal](https://support.discord.com/hc/en-us/requests/new?ticket_form_id=360000029731) youll probably get it back within 24 hours (at least thats what happened when i got rekt before). ill add a check so you cant leave your own server even though i kinda doubt that specifically caused it

**Comment by Maximal98** [comment]
welp, thanks for the heads up!

**Comment by ouwou** [comment]
theres also a couple loose ends as far as trying to mimic the web client like headers and cookies which when i get to should hopefully reduce this a bit
