### ISSUE TITLE
No build instructions for linux

### ISSUE THREAD

**Issue by i28v** [uowuo/abaddon#9]
There is no text after the "Mac/Linux: " build instructions

**Comment by lorpus** [comment]
i use windows and don't have any way to use linux right now so i can't do those for now. but if someone else wants to figure it out i can add it then

**Comment by koutsie** [comment]
vcpkg is hell.

**Comment by ouwou** [comment]
i've been working on this for a couple days and probably tomorrow or so it should be a lot easier to compile

**Comment by koutsie** [comment]
awesome!

**Comment by ouwou** [comment]
instructions are now in the README. you can also check https://github.com/uowuo/abaddon/blob/master/.github/workflows/ci.yml to see how CI builds it. let me know if there's any issues otherwise i'll probably close this soon
