### ISSUE TITLE
User data in program folder

### ISSUE THREAD

**Issue by c-sanchez** [uowuo/abaddon#92]
Please make the user data be stored in the same folder as the program, instead of the local appdata Windows folder
`%localappdata%\Temp\abaddon-cache`.

Or at least an option for the user who wants to do it this way, perhaps by detecting at abbadon startup whether or not there is a folder with a specific name, such as **`abaddon-cache`**.

This is more convenient as it makes the program "Portable", easy to maintain the session.

**Comment by ouwou** [comment]
well the only things that end up in that tmp folder are really temporary. everything in it is removed when the programs closed. its just the sqlite database whos purpose is to offload stuff from memory, downloaded images, and pasted images; nothing persists across sessions.
maybe you can be a bit more specific about what moving it next to the .exe would fix?

**Comment by c-sanchez** [comment]
I see, that being the case, I am fine with the way it is.
What I mean is that you should keep the login (token saved) in the same folder as abaddon.

For example to be able to use abaddon on a pendrive and always have the account/session available.

**Comment by ouwou** [comment]
the token is in abaddon.ini along with all other settings which should be placed wherever you ran the executable

**Comment by ouwou** [comment]
credential store has been a thing for a while. token is stored in cwd if compiled without keychain support. a new issue can be opened if theres any problems with portability
